export interface GrammarDrillQuestion {
  id: string;
  category: 'articles' | 'who-whom' | 'lay-lie' | 'fewer-less' | 'affect-effect' | 'subjunctive';
  question: string;
  options: string[];
  correct: string;
  explanation: string;
}

export const grammarDrillQuestions: GrammarDrillQuestion[] = [
  // ============================================================
  // ARTICLES (a / an / the / no article)
  // ============================================================
  {
    id: 'art-001',
    category: 'articles',
    question: 'She is ___ honest person.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: 'Use "an" before words that begin with a silent H. "Honest" starts with a vowel sound (/ˈɒnɪst/), so "an" is correct.',
  },
  {
    id: 'art-002',
    category: 'articles',
    question: 'He waited for ___ hour before the meeting started.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Hour" begins with a silent H, producing a vowel sound (/aʊər/). Use "an" before vowel sounds, not just vowel letters.',
  },
  {
    id: 'art-003',
    category: 'articles',
    question: 'I saw ___ dog in the park yesterday.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: 'When introducing a noun for the first time that is not yet known to the listener, use the indefinite article "a" (before consonant sounds).',
  },
  {
    id: 'art-004',
    category: 'articles',
    question: '___ dog I saw yesterday was a golden retriever.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: '"The" is used when referring to a specific noun already known to the listener — here, the dog mentioned previously.',
  },
  {
    id: 'art-005',
    category: 'articles',
    question: 'We had ___ lunch at noon.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'Meal names used in a general sense (breakfast, lunch, dinner) typically take no article. "We had lunch" is standard.',
  },
  {
    id: 'art-006',
    category: 'articles',
    question: '___ lunch she prepared was delicious.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'When a meal is modified or made specific ("the lunch she prepared"), the definite article is required because it refers to a particular instance.',
  },
  {
    id: 'art-007',
    category: 'articles',
    question: 'He plays ___ piano beautifully.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'the',
    explanation: 'Musical instruments typically take "the" when referring to playing them as a skill: "play the piano," "play the guitar."',
  },
  {
    id: 'art-008',
    category: 'articles',
    question: 'She is ___ European citizen.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: '"European" starts with a consonant sound (/jʊərəˈpiːən/), even though it begins with the letter E. Use "a" before consonant sounds.',
  },
  {
    id: 'art-009',
    category: 'articles',
    question: 'That was ___ unique opportunity.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: '"Unique" starts with a /juː/ sound (consonant Y sound), so "a" is correct despite the word starting with the letter U.',
  },
  {
    id: 'art-010',
    category: 'articles',
    question: 'He is ___ university professor.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: '"University" begins with /juː/, a consonant sound. Use "a" before consonant sounds regardless of the spelling.',
  },
  {
    id: 'art-011',
    category: 'articles',
    question: 'It was ___ understandable mistake.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Understandable" starts with a true vowel sound /ʌn/, unlike "university" or "unique." Use "an" here.',
  },
  {
    id: 'art-012',
    category: 'articles',
    question: '___ United Kingdom is an island nation.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Countries whose names include a political word (Kingdom, Republic, States) or a plural form take "the": the United Kingdom, the United States.',
  },
  {
    id: 'art-013',
    category: 'articles',
    question: 'They traveled to ___ France last summer.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'Most single-word country names take no article: France, Japan, Brazil. Exceptions include the Netherlands, the Philippines (plural forms).',
  },
  {
    id: 'art-014',
    category: 'articles',
    question: 'We sailed across ___ Atlantic Ocean.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'the',
    explanation: 'Oceans, seas, rivers, and mountain ranges take "the": the Atlantic, the Nile, the Rockies.',
  },
  {
    id: 'art-015',
    category: 'articles',
    question: 'They climbed ___ Mount Everest.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'Individual mountains and lakes typically take no article: Mount Everest, Lake Michigan. Contrast with mountain ranges: the Alps, the Andes.',
  },
  {
    id: 'art-016',
    category: 'articles',
    question: '___ Philippines is an archipelago.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Plural country names take "the": the Philippines, the Netherlands, the Maldives.',
  },
  {
    id: 'art-017',
    category: 'articles',
    question: 'She gave him ___ useful piece of advice.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: '"Useful" begins with the consonant sound /juː/. Like "unique" and "university," it takes "a" rather than "an."',
  },
  {
    id: 'art-018',
    category: 'articles',
    question: '___ water is essential for life.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'No article',
    explanation: 'Uncountable nouns used in a general sense take no article. "Water is essential for life" speaks about water universally.',
  },
  {
    id: 'art-019',
    category: 'articles',
    question: '___ water in this bottle tastes strange.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'When an uncountable noun is made specific ("in this bottle"), use "the." We are referring to particular water.',
  },
  {
    id: 'art-020',
    category: 'articles',
    question: 'He is ___ heir to a large fortune.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Heir" has a silent H (/ɛər/). Since it starts with a vowel sound, "an" is correct.',
  },
  {
    id: 'art-021',
    category: 'articles',
    question: 'She checked into ___ hotel near the airport.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: 'In standard modern English, the H in "hotel" is pronounced, so "a hotel" is correct. "An hotel" is an archaic British form.',
  },
  {
    id: 'art-022',
    category: 'articles',
    question: 'He sent ___ X-ray to the specialist.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: 'The letter X is pronounced "eks," starting with a vowel sound. Use "an" before abbreviations and letters that begin with vowel sounds.',
  },
  {
    id: 'art-023',
    category: 'articles',
    question: 'She earned ___ MBA from Harvard.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: 'MBA is pronounced "em-bee-ay." The first sound is /ɛm/, a vowel sound, so "an" is correct.',
  },
  {
    id: 'art-024',
    category: 'articles',
    question: '___ rich should help ___ poor.',
    options: ['The / the', 'A / a', 'The / a', 'No article / no article'],
    correct: 'The / the',
    explanation: '"The" + adjective can refer to an entire group of people: "the rich" (rich people), "the poor" (poor people). Both need "the."',
  },
  {
    id: 'art-025',
    category: 'articles',
    question: 'She was elected ___ president of the club.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'Titles used as complements of verbs like "elected," "appointed," or "made" typically drop the article when the position is unique: "elected president."',
  },
  {
    id: 'art-026',
    category: 'articles',
    question: '___ President of the United States lives in the White House.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'When a unique title is the subject of a sentence and refers to the specific officeholder, "the" is used: "The President lives in..."',
  },
  {
    id: 'art-027',
    category: 'articles',
    question: 'Life is ___ journey, not a destination.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: 'The indefinite article "a" is used to classify or define something: "Life is a journey" categorizes life as a type of journey.',
  },
  {
    id: 'art-028',
    category: 'articles',
    question: 'I need to go to ___ hospital. My friend is having surgery.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'the',
    explanation: 'In American English, "the hospital" is standard when going to visit or for a specific purpose. British English may drop the article when going as a patient.',
  },
  {
    id: 'art-029',
    category: 'articles',
    question: 'She goes to ___ church every Sunday.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'When "church" refers to the activity of worship rather than the building, no article is used: "go to church." Compare "go to the church" (the building).',
  },
  {
    id: 'art-030',
    category: 'articles',
    question: 'He plays ___ basketball after school.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'Sports and games take no article: "play basketball," "play chess." Contrast with instruments: "play the piano."',
  },
  {
    id: 'art-031',
    category: 'articles',
    question: '___ Sahara Desert is the largest hot desert in the world.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Deserts take the definite article: the Sahara, the Gobi, the Kalahari.',
  },
  {
    id: 'art-032',
    category: 'articles',
    question: 'He had ___ FBI agent at his door.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: 'FBI is pronounced "ef-bee-eye." The first sound is /ɛf/, a vowel sound, so "an" is correct.',
  },
  {
    id: 'art-033',
    category: 'articles',
    question: 'It was ___ one-time offer.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: '"One" starts with the consonant sound /w/. Despite the letter O, use "a" because article choice depends on sound, not spelling.',
  },
  {
    id: 'art-034',
    category: 'articles',
    question: 'She bought ___ umbrella at the shop.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Umbrella" starts with a true vowel sound /ʌm/. Use "an" before vowel sounds.',
  },
  {
    id: 'art-035',
    category: 'articles',
    question: 'We took a trip to ___ Bahamas.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'the',
    explanation: 'Island groups take "the": the Bahamas, the Canary Islands, the Maldives.',
  },
  {
    id: 'art-036',
    category: 'articles',
    question: '___ happiness cannot be bought.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'No article',
    explanation: 'Abstract nouns used in a general, universal sense take no article: "Happiness cannot be bought," "Love is blind."',
  },
  {
    id: 'art-037',
    category: 'articles',
    question: 'She is studying to be ___ engineer.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Engineer" starts with a vowel sound /ɛn/. When stating someone\'s profession with "be," use the indefinite article.',
  },
  {
    id: 'art-038',
    category: 'articles',
    question: 'Is there ___ life on Mars?',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: '"Life" as an uncountable, abstract concept takes no article: "Is there life on Mars?" We mean life in general, not a specific life.',
  },
  {
    id: 'art-039',
    category: 'articles',
    question: 'He drives ___ Uber for a living.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Uber" starts with a vowel sound /uː/. Despite being a brand name, it follows normal article rules based on pronunciation.',
  },
  {
    id: 'art-040',
    category: 'articles',
    question: 'She made ___ historic discovery.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: 'In standard modern English, the H in "historic" is pronounced, so "a historic" is correct. "An historic" persists in some dialects but is not standard.',
  },
  {
    id: 'art-041',
    category: 'articles',
    question: '___ English Channel separates England from France.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Bodies of water (channels, straits, seas, oceans) take "the": the English Channel, the Strait of Gibraltar.',
  },
  {
    id: 'art-042',
    category: 'articles',
    question: 'I listen to ___ radio on my commute.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'the',
    explanation: '"The radio" is idiomatic when referring to the medium of radio broadcasting, similar to "the internet" or "the news."',
  },
  {
    id: 'art-043',
    category: 'articles',
    question: 'She has ___ flu and cannot come to work.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'the',
    explanation: 'Certain illnesses idiomatically take "the": the flu, the measles, the mumps. Most other illnesses take no article: "She has cancer."',
  },
  {
    id: 'art-044',
    category: 'articles',
    question: 'They went to ___ bed early last night.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: '"Go to bed" (the activity of sleeping) takes no article, like "go to school" or "go to work." These are fixed expressions referring to the purpose, not the object.',
  },
  {
    id: 'art-045',
    category: 'articles',
    question: '___ sun rises in the east.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Unique celestial and natural objects take "the": the sun, the moon, the earth, the sky. There is only one sun in our context.',
  },
  {
    id: 'art-046',
    category: 'articles',
    question: 'He received ___ honorable mention at the competition.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: '"Honorable" has a silent H (/ˈɒnərəbəl/), beginning with a vowel sound. Use "an" before silent-H words.',
  },
  {
    id: 'art-047',
    category: 'articles',
    question: 'She gave ___ eulogy at the funeral.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'a',
    explanation: '"Eulogy" begins with the consonant sound /juː/, like "European" or "unique." Use "a" despite the vowel letter.',
  },
  {
    id: 'art-048',
    category: 'articles',
    question: '___ Nile is the longest river in Africa.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Rivers always take "the": the Nile, the Amazon, the Thames, the Mississippi.',
  },
  {
    id: 'art-049',
    category: 'articles',
    question: 'She plays ___ violin in ___ orchestra.',
    options: ['the / an', 'a / an', 'the / the', 'no article / an'],
    correct: 'the / an',
    explanation: 'Instruments take "the" when referring to the skill of playing: "plays the violin." An unspecified orchestra takes the indefinite article.',
  },
  {
    id: 'art-050',
    category: 'articles',
    question: 'What ___ unusual idea!',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'an',
    explanation: 'In exclamations with "What + article + adjective + noun," the article matches the adjective\'s sound. "Unusual" starts with a vowel sound, so "an" is correct.',
  },
  {
    id: 'art-051',
    category: 'articles',
    question: 'He was appointed ___ CEO of the company.',
    options: ['a', 'an', 'the', 'no article'],
    correct: 'no article',
    explanation: 'Like other unique titles used as complements of appointing verbs, the article is dropped: "appointed CEO," "named chairman."',
  },
  {
    id: 'art-052',
    category: 'articles',
    question: '___ Alps are popular with skiers.',
    options: ['A', 'An', 'The', 'No article'],
    correct: 'The',
    explanation: 'Mountain ranges take "the": the Alps, the Rockies, the Himalayas. Individual peaks do not: Mount Blanc, Mount Fuji.',
  },

  // ============================================================
  // WHO / WHOM
  // ============================================================
  {
    id: 'ww-001',
    category: 'who-whom',
    question: '___ is coming to the party tonight?',
    options: ['Who', 'Whom'],
    correct: 'Who',
    explanation: '"Who" is the subject of the verb "is coming." Subjects perform the action. Test: "He is coming" (not "Him is coming").',
  },
  {
    id: 'ww-002',
    category: 'who-whom',
    question: '___ did you invite to the party?',
    options: ['Who', 'Whom'],
    correct: 'Whom',
    explanation: '"Whom" is the object of "invite." You invited him/her (object), not he/she. When in doubt, substitute he/him — "him" maps to "whom."',
  },
  {
    id: 'ww-003',
    category: 'who-whom',
    question: 'The teacher ___ assigned the homework is absent today.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: '"Who" is the subject of "assigned." The teacher assigned the homework — she/he did the assigning.',
  },
  {
    id: 'ww-004',
    category: 'who-whom',
    question: 'The teacher ___ the students admire is retiring.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"Whom" is the object of "admire." The students admire him/her. The students are the subject; the teacher is the object of their admiration.',
  },
  {
    id: 'ww-005',
    category: 'who-whom',
    question: 'To ___ should I address this letter?',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"Whom" follows a preposition. "To whom" is correct because the pronoun is the object of "to." You would address it to him, not to he.',
  },
  {
    id: 'ww-006',
    category: 'who-whom',
    question: '___ do you think will win the election?',
    options: ['Who', 'Whom'],
    correct: 'Who',
    explanation: 'This is tricky. "Do you think" is a parenthetical. Remove it: "___ will win the election?" The pronoun is the subject of "will win," so "who" is correct.',
  },
  {
    id: 'ww-007',
    category: 'who-whom',
    question: 'She is the candidate ___ I believe is most qualified.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: '"I believe" is a parenthetical clause. Remove it: "She is the candidate ___ is most qualified." The pronoun is the subject of "is," so "who" is correct.',
  },
  {
    id: 'ww-008',
    category: 'who-whom',
    question: 'The man with ___ she spoke was her lawyer.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"Whom" is the object of the preposition "with." She spoke with him. Prepositions always take the objective case.',
  },
  {
    id: 'ww-009',
    category: 'who-whom',
    question: '___ shall I say is calling?',
    options: ['Who', 'Whom'],
    correct: 'Who',
    explanation: '"Shall I say" is a parenthetical. Remove it: "___ is calling?" The pronoun is the subject of "is calling," so "who" is correct.',
  },
  {
    id: 'ww-010',
    category: 'who-whom',
    question: 'Give the package to ___ answers the door.',
    options: ['whoever', 'whomever'],
    correct: 'whoever',
    explanation: 'The entire clause "whoever answers the door" is the object of "to." Within that clause, the pronoun is the subject of "answers," so "whoever" is correct.',
  },
  {
    id: 'ww-011',
    category: 'who-whom',
    question: 'Give the package to ___ you see first.',
    options: ['whoever', 'whomever'],
    correct: 'whomever',
    explanation: 'Within the clause "whomever you see first," "you" is the subject and the pronoun is the object of "see." You see him/her, so "whomever" is correct.',
  },
  {
    id: 'ww-012',
    category: 'who-whom',
    question: '___ the committee selects will lead the project.',
    options: ['Whoever', 'Whomever'],
    correct: 'Whomever',
    explanation: 'Within the noun clause, "the committee" is the subject of "selects" and the pronoun is its object. The committee selects him/her, so "whomever."',
  },
  {
    id: 'ww-013',
    category: 'who-whom',
    question: 'I don\'t know ___ left the door open.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: 'The pronoun is the subject of "left." Someone left the door open — he/she did it. Subjects take "who."',
  },
  {
    id: 'ww-014',
    category: 'who-whom',
    question: 'The woman ___ purse was stolen filed a report.',
    options: ['who', 'whom', 'whose'],
    correct: 'whose',
    explanation: '"Whose" shows possession — the purse belongs to the woman. Neither "who" nor "whom" can show ownership.',
  },
  {
    id: 'ww-015',
    category: 'who-whom',
    question: 'She asked ___ the message was for.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'The message was for him/her. "Whom" is the object of the preposition "for," even though the preposition is stranded at the end.',
  },
  {
    id: 'ww-016',
    category: 'who-whom',
    question: '___ did the manager promote?',
    options: ['Who', 'Whom'],
    correct: 'Whom',
    explanation: 'The manager promoted him/her. The pronoun is the direct object of "promote," so use "whom."',
  },
  {
    id: 'ww-017',
    category: 'who-whom',
    question: 'The artist ___ painted this mural is famous worldwide.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: 'The artist painted the mural — he/she is the subject of "painted." Use "who" for subjects.',
  },
  {
    id: 'ww-018',
    category: 'who-whom',
    question: 'He is someone ___ I deeply respect.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'I respect him. The pronoun is the object of "respect." Use "whom" for objects of verbs.',
  },
  {
    id: 'ww-019',
    category: 'who-whom',
    question: '___ among us has never made a mistake?',
    options: ['Who', 'Whom'],
    correct: 'Who',
    explanation: 'The pronoun is the subject of "has made." "Among us" is a prepositional phrase modifying the subject, not determining its case.',
  },
  {
    id: 'ww-020',
    category: 'who-whom',
    question: 'The volunteers, many of ___ were students, worked tirelessly.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"Of whom" — the pronoun is the object of the preposition "of." Many of them were students.',
  },
  {
    id: 'ww-021',
    category: 'who-whom',
    question: 'She married a man ___ everyone thought was wealthy.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: '"Everyone thought" is parenthetical. Remove it: "a man ___ was wealthy." The pronoun is the subject of "was," so "who" is correct.',
  },
  {
    id: 'ww-022',
    category: 'who-whom',
    question: '___ are you going to recommend for the position?',
    options: ['Who', 'Whom'],
    correct: 'Whom',
    explanation: 'You are going to recommend him/her. The pronoun is the object of "recommend." Use "whom."',
  },
  {
    id: 'ww-023',
    category: 'who-whom',
    question: 'I will support ___ is chosen by the committee.',
    options: ['whoever', 'whomever'],
    correct: 'whoever',
    explanation: 'Within the noun clause, the pronoun is the subject of "is chosen." The clause as a whole serves as the object of "support," but internal grammar determines the case.',
  },
  {
    id: 'ww-024',
    category: 'who-whom',
    question: 'Tell me ___ you think we should hire.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"You think" is parenthetical. Remove it: "Tell me ___ we should hire." We should hire him/her — the pronoun is the object, so "whom."',
  },
  {
    id: 'ww-025',
    category: 'who-whom',
    question: 'The player ___ scores the most points wins the trophy.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: 'The player scores — he/she is the subject of "scores." Use "who" for subjects.',
  },
  {
    id: 'ww-026',
    category: 'who-whom',
    question: 'For ___ is this gift intended?',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"For whom" — the pronoun is the object of "for." The gift is intended for him/her.',
  },
  {
    id: 'ww-027',
    category: 'who-whom',
    question: 'The author ___ book became a bestseller was invited to speak.',
    options: ['who', 'whom', 'whose'],
    correct: 'whose',
    explanation: '"Whose" indicates possession — the book belongs to the author. "Who" and "whom" cannot express ownership.',
  },
  {
    id: 'ww-028',
    category: 'who-whom',
    question: 'She is the one ___ I was telling you about.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'I was telling you about her. The pronoun is the object of "about," so use "whom."',
  },
  {
    id: 'ww-029',
    category: 'who-whom',
    question: '___ would you rather work with — Sarah or James?',
    options: ['Who', 'Whom'],
    correct: 'Whom',
    explanation: 'You would rather work with him/her. The pronoun is the object of "with." Use "whom."',
  },
  {
    id: 'ww-030',
    category: 'who-whom',
    question: 'The CEO, ___ was once a janitor, gave an inspiring speech.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: 'The CEO was once a janitor — he/she is the subject of "was." Use "who."',
  },
  {
    id: 'ww-031',
    category: 'who-whom',
    question: 'Hire ___ you feel is the best candidate.',
    options: ['whoever', 'whomever'],
    correct: 'whoever',
    explanation: '"You feel" is parenthetical. The pronoun is the subject of "is": "___ is the best candidate." Use "whoever."',
  },
  {
    id: 'ww-032',
    category: 'who-whom',
    question: 'Between you and me, ___ do you think started the rumor?',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: '"Do you think" is parenthetical. Remove it: "___ started the rumor?" The pronoun is the subject of "started," so "who."',
  },
  {
    id: 'ww-033',
    category: 'who-whom',
    question: 'The witness ___ the detective interviewed changed her story.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'The detective interviewed her. "The detective" is the subject, and the pronoun is the object of "interviewed." Use "whom."',
  },
  {
    id: 'ww-034',
    category: 'who-whom',
    question: '___ broke the window will have to pay for it.',
    options: ['Whoever', 'Whomever'],
    correct: 'Whoever',
    explanation: 'The pronoun is the subject of "broke" within the noun clause. He/she broke the window. Use "whoever."',
  },
  {
    id: 'ww-035',
    category: 'who-whom',
    question: 'The lawyer ___ the firm assigned to the case is very experienced.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'The firm assigned him/her. The pronoun is the object of "assigned." Use "whom."',
  },
  {
    id: 'ww-036',
    category: 'who-whom',
    question: 'She wondered ___ had sent the anonymous letter.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: 'Someone sent the letter — he/she is the subject of "had sent." Use "who."',
  },
  {
    id: 'ww-037',
    category: 'who-whom',
    question: 'The doctor ___ I was referred to is booked for months.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'I was referred to him/her. The pronoun is the object of "to." Use "whom."',
  },
  {
    id: 'ww-038',
    category: 'who-whom',
    question: '___ did you say called while I was out?',
    options: ['Who', 'Whom'],
    correct: 'Who',
    explanation: '"Did you say" is parenthetical. Remove it: "___ called while I was out?" The pronoun is the subject of "called," so "who."',
  },
  {
    id: 'ww-039',
    category: 'who-whom',
    question: 'She will mentor ___ needs the most guidance.',
    options: ['whoever', 'whomever'],
    correct: 'whoever',
    explanation: 'Within the noun clause, the pronoun is the subject of "needs." He/she needs guidance. Use "whoever."',
  },
  {
    id: 'ww-040',
    category: 'who-whom',
    question: 'It depends on ___ the voters choose.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'The voters choose him/her. The pronoun is the object of "choose." The preposition "on" governs the whole clause, but internal grammar determines the case.',
  },
  {
    id: 'ww-041',
    category: 'who-whom',
    question: '___ is responsible for this mess?',
    options: ['Who', 'Whom'],
    correct: 'Who',
    explanation: 'The pronoun is the subject of "is." He/she is responsible. Use "who."',
  },
  {
    id: 'ww-042',
    category: 'who-whom',
    question: 'He is the colleague ___ I collaborate with most often.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'I collaborate with him. The pronoun is the object of "with." Use "whom."',
  },
  {
    id: 'ww-043',
    category: 'who-whom',
    question: 'The scholarship goes to ___ writes the best essay.',
    options: ['whoever', 'whomever'],
    correct: 'whoever',
    explanation: 'The pronoun is the subject of "writes." He/she writes the best essay. Use "whoever."',
  },
  {
    id: 'ww-044',
    category: 'who-whom',
    question: 'I need someone on ___ I can rely.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'I can rely on him/her. The pronoun is the object of the preposition "on." Use "whom."',
  },
  {
    id: 'ww-045',
    category: 'who-whom',
    question: 'The guests, some of ___ arrived late, enjoyed the dinner.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: '"Of whom" — the pronoun is the object of "of." Some of them arrived late.',
  },
  {
    id: 'ww-046',
    category: 'who-whom',
    question: '___ we elect will shape the nation\'s future.',
    options: ['Whoever', 'Whomever'],
    correct: 'Whomever',
    explanation: 'Within the clause, "we" is the subject of "elect" and the pronoun is the object. We elect him/her. Use "whomever." The clause itself serves as the sentence subject.',
  },
  {
    id: 'ww-047',
    category: 'who-whom',
    question: 'She is someone ___ I think will go far in life.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: '"I think" is parenthetical. Remove it: "She is someone ___ will go far." The pronoun is the subject of "will go." Use "who."',
  },
  {
    id: 'ww-048',
    category: 'who-whom',
    question: 'The patient ___ the nurse attended to recovered quickly.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'The nurse attended to him/her. "The nurse" is the subject, and the pronoun is the object of "attended to." Use "whom."',
  },
  {
    id: 'ww-049',
    category: 'who-whom',
    question: 'It doesn\'t matter ___ gets credit, as long as the work gets done.',
    options: ['who', 'whom'],
    correct: 'who',
    explanation: 'The pronoun is the subject of "gets." He/she gets credit. Use "who."',
  },
  {
    id: 'ww-050',
    category: 'who-whom',
    question: 'The singer ___ fans adore just released a new album.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'Fans adore him/her. The pronoun is the object of "adore." Use "whom."',
  },
  {
    id: 'ww-051',
    category: 'who-whom',
    question: 'She asked me ___ I would rather be stranded on an island with.',
    options: ['who', 'whom'],
    correct: 'whom',
    explanation: 'I would rather be stranded with him/her. The pronoun is the object of "with." Use "whom."',
  },
  {
    id: 'ww-052',
    category: 'who-whom',
    question: 'The prize will go to ___ the judges consider most deserving.',
    options: ['whoever', 'whomever'],
    correct: 'whomever',
    explanation: 'The judges consider him/her most deserving. Within the clause, the pronoun is the object of "consider." Use "whomever."',
  },

  // ============================================================
  // LAY / LIE
  // ============================================================
  {
    id: 'll-001',
    category: 'lay-lie',
    question: 'Please ___ the book on the table.',
    options: ['lay', 'lie'],
    correct: 'lay',
    explanation: '"Lay" means to place something down and requires a direct object. Here, the object is "the book." You lay something somewhere.',
  },
  {
    id: 'll-002',
    category: 'lay-lie',
    question: 'I need to ___ down for a while.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: '"Lie" means to recline and does not take a direct object. You lie down (yourself). "Lay down" requires an object — you lay something down.',
  },
  {
    id: 'll-003',
    category: 'lay-lie',
    question: 'The cat was ___ on the windowsill all afternoon.',
    options: ['laying', 'lying'],
    correct: 'lying',
    explanation: 'The cat was reclining (no object). "Lying" is the present participle of "lie." "Laying" would require an object (laying eggs, for example).',
  },
  {
    id: 'll-004',
    category: 'lay-lie',
    question: 'She ___ the baby in the crib gently.',
    options: ['laid', 'lay', 'lied'],
    correct: 'laid',
    explanation: '"Laid" is the past tense of "lay" (to place). She placed the baby down. "Lay" is the present tense. "Lied" means told an untruth.',
  },
  {
    id: 'll-005',
    category: 'lay-lie',
    question: 'He ___ on the couch all day yesterday.',
    options: ['laid', 'lay', 'lied'],
    correct: 'lay',
    explanation: 'Confusingly, "lay" is also the past tense of "lie" (to recline). He reclined on the couch yesterday. He lay there.',
  },
  {
    id: 'll-006',
    category: 'lay-lie',
    question: 'The dog has ___ in that spot for hours.',
    options: ['laid', 'lain', 'lied'],
    correct: 'lain',
    explanation: '"Lain" is the past participle of "lie" (to recline). With "has/have," use "lain": "has lain," "have lain." "Laid" is the past participle of "lay."',
  },
  {
    id: 'll-007',
    category: 'lay-lie',
    question: 'She has ___ the groundwork for the project.',
    options: ['laid', 'lain', 'lied'],
    correct: 'laid',
    explanation: '"Laid" is the past participle of "lay" (to place). With "has/have" and an object: "has laid the groundwork." "Lain" has no object.',
  },
  {
    id: 'll-008',
    category: 'lay-lie',
    question: 'The hens are ___ eggs in the barn.',
    options: ['laying', 'lying'],
    correct: 'laying',
    explanation: '"Laying" requires a direct object, and here the object is "eggs." Hens lay eggs. "Lying" means reclining.',
  },
  {
    id: 'll-009',
    category: 'lay-lie',
    question: 'He ___ about his qualifications on his resume.',
    options: ['laid', 'lay', 'lied'],
    correct: 'lied',
    explanation: '"Lied" is the past tense of "lie" meaning to tell an untruth. This is a third verb entirely: lie/lied/lied (to be dishonest).',
  },
  {
    id: 'll-010',
    category: 'lay-lie',
    question: 'Don\'t just ___ there — do something!',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: '"Lie" means to recline with no object. The person is reclining (themselves). "Lay there" would need an object.',
  },
  {
    id: 'll-011',
    category: 'lay-lie',
    question: 'She ___ awake all night worrying.',
    options: ['laid', 'lay', 'lied'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to recline). She was reclining awake. No object is involved.',
  },
  {
    id: 'll-012',
    category: 'lay-lie',
    question: 'The workers are ___ new carpet in the hallway.',
    options: ['laying', 'lying'],
    correct: 'laying',
    explanation: '"Laying" takes an object — here, "new carpet." They are placing carpet down. "Lying carpet" would be incorrect.',
  },
  {
    id: 'll-013',
    category: 'lay-lie',
    question: 'He had ___ the blame on his coworker unfairly.',
    options: ['laid', 'lain'],
    correct: 'laid',
    explanation: '"Laid" is the past participle of "lay" (to place). "The blame" is the direct object. He placed the blame on someone.',
  },
  {
    id: 'll-014',
    category: 'lay-lie',
    question: 'The old mansion has ___ abandoned for decades.',
    options: ['laid', 'lain'],
    correct: 'lain',
    explanation: '"Lain" is the past participle of "lie" (to be in a state/position). The mansion has been sitting abandoned — no object is involved.',
  },
  {
    id: 'll-015',
    category: 'lay-lie',
    question: 'She told the dog to ___ down.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: 'The dog is reclining itself — no object. "Lie down" is correct. Many people say "lay down" informally, but it is grammatically incorrect without an object.',
  },
  {
    id: 'll-016',
    category: 'lay-lie',
    question: '___ your cards on the table.',
    options: ['Lay', 'Lie'],
    correct: 'Lay',
    explanation: '"Lay" takes a direct object — "your cards." You are placing them down. "Lie your cards" is incorrect.',
  },
  {
    id: 'll-017',
    category: 'lay-lie',
    question: 'The ruins ___ hidden beneath the city for centuries.',
    options: ['laid', 'lay', 'lied'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to be situated). The ruins were situated/resting beneath the city. No object.',
  },
  {
    id: 'll-018',
    category: 'lay-lie',
    question: 'After lunch, I usually ___ down for a nap.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: 'You recline yourself — no direct object. "Lie down" is correct in the present tense. "I lay down" would be past tense of "lie."',
  },
  {
    id: 'll-019',
    category: 'lay-lie',
    question: 'The bricklayer ___ fifty bricks before noon yesterday.',
    options: ['laid', 'lay'],
    correct: 'laid',
    explanation: '"Laid" is the past tense of "lay" (to place). "Fifty bricks" is the direct object. He placed fifty bricks.',
  },
  {
    id: 'll-020',
    category: 'lay-lie',
    question: 'The responsibility ___ with the manager.',
    options: ['lays', 'lies'],
    correct: 'lies',
    explanation: '"Lies" (present tense of "lie") means to rest or be situated. Responsibility rests with the manager — no object is placed anywhere.',
  },
  {
    id: 'll-021',
    category: 'lay-lie',
    question: 'She has been ___ in bed with the flu all week.',
    options: ['laying', 'lying'],
    correct: 'lying',
    explanation: 'She is reclining in bed — no direct object. "Lying" is the present participle of "lie." "Laying" would need an object.',
  },
  {
    id: 'll-022',
    category: 'lay-lie',
    question: 'The treasure had ___ undiscovered for centuries.',
    options: ['laid', 'lain'],
    correct: 'lain',
    explanation: '"Lain" is the past participle of "lie" (to be situated). The treasure was resting undiscovered — no object.',
  },
  {
    id: 'll-023',
    category: 'lay-lie',
    question: 'Now I ___ me down to sleep.',
    options: ['lay', 'lie'],
    correct: 'lay',
    explanation: 'In this famous prayer, "me" is the direct object. You are laying (placing) yourself down. When there is a reflexive object, "lay" is correct.',
  },
  {
    id: 'll-024',
    category: 'lay-lie',
    question: 'The problem ___ in the foundation of the argument.',
    options: ['lays', 'lies'],
    correct: 'lies',
    explanation: '"Lies" means to be situated or exist. The problem exists in the foundation. "Lays" would require a direct object.',
  },
  {
    id: 'll-025',
    category: 'lay-lie',
    question: 'She ___ the wreath on the grave.',
    options: ['laid', 'lay'],
    correct: 'laid',
    explanation: '"Laid" is the past tense of "lay" (to place). "The wreath" is the direct object being placed.',
  },
  {
    id: 'll-026',
    category: 'lay-lie',
    question: 'He has ___ to us about his whereabouts.',
    options: ['laid', 'lain', 'lied'],
    correct: 'lied',
    explanation: '"Lied" is the past participle of "lie" (to tell an untruth). Lie/lied/lied is completely regular when it means to be dishonest.',
  },
  {
    id: 'll-027',
    category: 'lay-lie',
    question: 'The valley ___ between two mountain ranges.',
    options: ['lays', 'lies'],
    correct: 'lies',
    explanation: '"Lies" means to be situated geographically. The valley is positioned between the ranges — no object is being placed.',
  },
  {
    id: 'll-028',
    category: 'lay-lie',
    question: 'I ___ awake last night thinking about the test.',
    options: ['laid', 'lay'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to recline). I was reclining awake. No direct object.',
  },
  {
    id: 'll-029',
    category: 'lay-lie',
    question: 'The mechanic was ___ under the car when we arrived.',
    options: ['laying', 'lying'],
    correct: 'lying',
    explanation: 'The mechanic was positioned/reclining under the car — no direct object. "Lying" is correct.',
  },
  {
    id: 'll-030',
    category: 'lay-lie',
    question: 'Please ___ your weapons down.',
    options: ['lay', 'lie'],
    correct: 'lay',
    explanation: '"Lay" requires a direct object — "your weapons." You are placing them down. "Lie your weapons down" is incorrect.',
  },
  {
    id: 'll-031',
    category: 'lay-lie',
    question: 'The snow ___ thick on the ground this morning.',
    options: ['laid', 'lay'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to rest/be situated). The snow was resting on the ground. No object.',
  },
  {
    id: 'll-032',
    category: 'lay-lie',
    question: 'She had ___ the foundation for her career years earlier.',
    options: ['laid', 'lain'],
    correct: 'laid',
    explanation: '"Laid" is the past participle of "lay" (to place/establish). "The foundation" is the direct object.',
  },
  {
    id: 'll-033',
    category: 'lay-lie',
    question: 'The documents have ___ untouched on his desk for weeks.',
    options: ['laid', 'lain'],
    correct: 'lain',
    explanation: '"Lain" is the past participle of "lie" (to be situated). The documents were resting on the desk — no one placed them as the focus of the sentence.',
  },
  {
    id: 'll-034',
    category: 'lay-lie',
    question: 'Stop ___ around and help me clean up.',
    options: ['laying', 'lying'],
    correct: 'lying',
    explanation: 'The person is reclining/lounging — no direct object. "Lying around" means being idle. "Laying around" would need an object.',
  },
  {
    id: 'll-035',
    category: 'lay-lie',
    question: 'The answer ___ somewhere in these files.',
    options: ['lays', 'lies'],
    correct: 'lies',
    explanation: '"Lies" means to be found or situated. The answer exists somewhere. "Lays" would need a direct object.',
  },
  {
    id: 'll-036',
    category: 'lay-lie',
    question: 'She ___ the map out on the table and studied it.',
    options: ['laid', 'lay'],
    correct: 'laid',
    explanation: '"Laid" is the past tense of "lay" (to spread out/place). "The map" is the direct object.',
  },
  {
    id: 'll-037',
    category: 'lay-lie',
    question: 'The fault ___ entirely with management.',
    options: ['lays', 'lies'],
    correct: 'lies',
    explanation: '"Lies" means to rest or be attributable. Fault rests with management. No object is placed.',
  },
  {
    id: 'll-038',
    category: 'lay-lie',
    question: 'My keys were ___ right where I left them.',
    options: ['laying', 'lying'],
    correct: 'lying',
    explanation: 'The keys were situated/resting in a location — no direct object. "Lying" is correct.',
  },
  {
    id: 'll-039',
    category: 'lay-lie',
    question: 'He ___ the trap carefully in the woods.',
    options: ['laid', 'lay'],
    correct: 'laid',
    explanation: '"Laid" is the past tense of "lay" (to set/place). "The trap" is the direct object being placed.',
  },
  {
    id: 'll-040',
    category: 'lay-lie',
    question: 'She will ___ in the sun all afternoon if you let her.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: 'She will recline in the sun — no object. "Lie" is correct for the future tense of reclining.',
  },
  {
    id: 'll-041',
    category: 'lay-lie',
    question: 'The city ___ in ruins after the earthquake.',
    options: ['laid', 'lay'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to be situated). The city was in a state of ruin — no direct object.',
  },
  {
    id: 'll-042',
    category: 'lay-lie',
    question: 'Let sleeping dogs ___.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: 'The dogs are reclining/sleeping — no direct object. "Let sleeping dogs lie" is a proverb meaning to leave things as they are.',
  },
  {
    id: 'll-043',
    category: 'lay-lie',
    question: 'She has been ___ tiles in the bathroom all day.',
    options: ['laying', 'lying'],
    correct: 'laying',
    explanation: '"Laying" takes a direct object — "tiles." She has been placing tiles. "Lying tiles" would be incorrect.',
  },
  {
    id: 'll-044',
    category: 'lay-lie',
    question: 'The ship had ___ at the bottom of the ocean for a century.',
    options: ['laid', 'lain'],
    correct: 'lain',
    explanation: '"Lain" is the past participle of "lie" (to be situated). The ship was resting at the bottom — no object.',
  },
  {
    id: 'll-045',
    category: 'lay-lie',
    question: 'He ___ the newspaper aside and stood up.',
    options: ['laid', 'lay'],
    correct: 'laid',
    explanation: '"Laid" is the past tense of "lay" (to place). "The newspaper" is the direct object.',
  },
  {
    id: 'll-046',
    category: 'lay-lie',
    question: 'As the land ___ fallow, wildflowers began to bloom.',
    options: ['laid', 'lay'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to be in a state). The land was in a fallow state — no object.',
  },
  {
    id: 'll-047',
    category: 'lay-lie',
    question: 'She asked the child to ___ still during the exam.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: 'The child is reclining still — no object. "Lie still" means to remain in a reclining position without moving.',
  },
  {
    id: 'll-048',
    category: 'lay-lie',
    question: 'I plan to ___ a new patio this summer.',
    options: ['lay', 'lie'],
    correct: 'lay',
    explanation: '"Lay" takes an object — "a new patio." You are placing/building the patio. "Lie a patio" is incorrect.',
  },
  {
    id: 'll-049',
    category: 'lay-lie',
    question: 'The truth ___ hidden beneath layers of deception.',
    options: ['laid', 'lay'],
    correct: 'lay',
    explanation: '"Lay" is the past tense of "lie" (to be concealed/situated). The truth was hidden — no direct object.',
  },
  {
    id: 'll-050',
    category: 'lay-lie',
    question: 'He was accused of ___ under oath.',
    options: ['laying', 'lying'],
    correct: 'lying',
    explanation: '"Lying" here means telling an untruth — the third meaning of "lie." Lie/lied/lied (to be dishonest). Present participle: lying.',
  },
  {
    id: 'll-051',
    category: 'lay-lie',
    question: 'After the long hike, we all just wanted to ___ down.',
    options: ['lay', 'lie'],
    correct: 'lie',
    explanation: 'We wanted to recline — no object. "Lie down" is correct. This is one of the most common errors in English.',
  },
  {
    id: 'll-052',
    category: 'lay-lie',
    question: 'The opportunity ___ before us, and we must seize it.',
    options: ['lays', 'lies'],
    correct: 'lies',
    explanation: '"Lies" means to exist or be situated. The opportunity is before us — no object. "Lays" would need something being placed.',
  },

  // ============================================================
  // FEWER / LESS
  // ============================================================
  {
    id: 'fl-001',
    category: 'fewer-less',
    question: 'There are ___ apples in the basket than yesterday.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: 'Use "fewer" with countable nouns. Apples can be counted individually: one apple, two apples.',
  },
  {
    id: 'fl-002',
    category: 'fewer-less',
    question: 'There is ___ water in the lake than last year.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'Use "less" with uncountable (mass) nouns. Water is measured, not counted individually.',
  },
  {
    id: 'fl-003',
    category: 'fewer-less',
    question: 'She earns ___ money than her brother.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Money" is uncountable — you say "much money," not "many moneys." Use "less" with uncountable nouns.',
  },
  {
    id: 'fl-004',
    category: 'fewer-less',
    question: 'He has ___ friends than he used to.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Friends" is countable — you can have one friend, two friends, etc. Use "fewer" with countable plural nouns.',
  },
  {
    id: 'fl-005',
    category: 'fewer-less',
    question: 'We have ___ than 10 minutes to finish.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'When a number represents a single quantity or measurement (10 minutes as a block of time), "less" is standard. Time expressions like "less than 10 minutes" treat time as continuous.',
  },
  {
    id: 'fl-006',
    category: 'fewer-less',
    question: 'The new policy resulted in ___ accidents on the highway.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Accidents" is countable. You can count individual accidents. Use "fewer."',
  },
  {
    id: 'fl-007',
    category: 'fewer-less',
    question: 'I have ___ patience for this than I used to.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Patience" is uncountable — an abstract quality measured in degree, not in individual units. Use "less."',
  },
  {
    id: 'fl-008',
    category: 'fewer-less',
    question: 'The express lane is for customers with ___ than 15 items.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Items" is countable. You can count 1, 2, 3 items. Use "fewer." (Many store signs say "less," but "fewer" is grammatically correct.)',
  },
  {
    id: 'fl-009',
    category: 'fewer-less',
    question: 'It costs ___ than $50.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'Money amounts are treated as a singular quantity. "$50" is a lump sum, not individual dollars. "Less than $50" is standard.',
  },
  {
    id: 'fl-010',
    category: 'fewer-less',
    question: 'The recipe calls for ___ sugar than the original.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Sugar" is uncountable. You measure sugar (a cup, a teaspoon), not count individual sugars. Use "less."',
  },
  {
    id: 'fl-011',
    category: 'fewer-less',
    question: 'There are ___ cars on the road at night.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Cars" is countable. You can count individual cars. Use "fewer."',
  },
  {
    id: 'fl-012',
    category: 'fewer-less',
    question: 'She drank ___ coffee today than usual.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Coffee" as a substance is uncountable. Use "less." (If you meant individual cups: "She drank fewer cups of coffee.")',
  },
  {
    id: 'fl-013',
    category: 'fewer-less',
    question: 'No ___ than fifty people attended the meeting.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"People" is countable, and "no fewer than" emphasizes the count being at least fifty. "No less than" is sometimes used for emphasis regardless of countability, but "fewer" is precise here.',
  },
  {
    id: 'fl-014',
    category: 'fewer-less',
    question: 'The diet promises ___ fat and ___ calories.',
    options: ['less / fewer', 'fewer / less', 'less / less', 'fewer / fewer'],
    correct: 'less / fewer',
    explanation: '"Fat" is uncountable (a substance) — use "less." "Calories" are countable units — use "fewer."',
  },
  {
    id: 'fl-015',
    category: 'fewer-less',
    question: 'He weighs ___ than his brother.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'Weight is a continuous measurement, not individual countable units. Use "less." You weigh less, not fewer.',
  },
  {
    id: 'fl-016',
    category: 'fewer-less',
    question: 'There are ___ opportunities available this year.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Opportunities" is countable — one opportunity, two opportunities. Use "fewer."',
  },
  {
    id: 'fl-017',
    category: 'fewer-less',
    question: 'He sleeps ___ than six hours a night.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: 'When referring to individual countable units of time ("six hours" as 6 distinct hours), "fewer" is correct. Compare "less than an hour" (a continuous span).',
  },
  {
    id: 'fl-018',
    category: 'fewer-less',
    question: 'The new formula requires ___ steps.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Steps" is countable. You can count step 1, step 2, step 3. Use "fewer."',
  },
  {
    id: 'fl-019',
    category: 'fewer-less',
    question: 'We have ___ time than I thought.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Time" is uncountable in this sense — a continuous quantity, not discrete units. Use "less."',
  },
  {
    id: 'fl-020',
    category: 'fewer-less',
    question: 'She made ___ mistakes on the second attempt.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Mistakes" is countable. One mistake, two mistakes. Use "fewer."',
  },
  {
    id: 'fl-021',
    category: 'fewer-less',
    question: 'The project took ___ than two years.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Two years" represents a single span of time. When treating a duration as one lump quantity, "less" is standard: "less than two years."',
  },
  {
    id: 'fl-022',
    category: 'fewer-less',
    question: 'There is ___ noise in the library than in the cafeteria.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Noise" is uncountable — an amorphous quantity measured in degree. Use "less."',
  },
  {
    id: 'fl-023',
    category: 'fewer-less',
    question: 'He ate ___ cookies than his sister.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Cookies" is countable. You can count individual cookies. Use "fewer."',
  },
  {
    id: 'fl-024',
    category: 'fewer-less',
    question: 'The road is ___ than a mile long.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'Distance is a continuous measurement. "Less than a mile" treats the distance as a single quantity. Use "less."',
  },
  {
    id: 'fl-025',
    category: 'fewer-less',
    question: '___ people voted in the midterm election than in the presidential one.',
    options: ['Fewer', 'Less'],
    correct: 'Fewer',
    explanation: '"People" is countable (one person, two people). Use "fewer."',
  },
  {
    id: 'fl-026',
    category: 'fewer-less',
    question: 'Use ___ butter in the recipe if you want it lighter.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Butter" is uncountable — a mass noun. Use "less."',
  },
  {
    id: 'fl-027',
    category: 'fewer-less',
    question: 'She has ___ experience than the other applicants.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Experience" (in this general sense) is uncountable. You have more or less experience, not fewer experience.',
  },
  {
    id: 'fl-028',
    category: 'fewer-less',
    question: 'There are ___ words in this essay than required.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Words" is countable. You can count individual words. Use "fewer."',
  },
  {
    id: 'fl-029',
    category: 'fewer-less',
    question: 'He drank ___ glasses of wine than usual.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Glasses" is countable — one glass, two glasses. Use "fewer." (But "less wine" because wine itself is uncountable.)',
  },
  {
    id: 'fl-030',
    category: 'fewer-less',
    question: 'The company laid off no ___ than a hundred workers.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Workers" is countable. "No fewer than" means "at least" and is correct with countable nouns.',
  },
  {
    id: 'fl-031',
    category: 'fewer-less',
    question: 'She spends ___ than $200 a month on groceries.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'Dollar amounts are treated as a single sum. "$200" is a lump quantity. Use "less."',
  },
  {
    id: 'fl-032',
    category: 'fewer-less',
    question: 'Try to use ___ adjectives in your writing.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Adjectives" is countable. You can count individual adjectives. Use "fewer."',
  },
  {
    id: 'fl-033',
    category: 'fewer-less',
    question: 'The smaller engine uses ___ fuel.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Fuel" is uncountable — a mass noun. Use "less."',
  },
  {
    id: 'fl-034',
    category: 'fewer-less',
    question: 'He made ___ than $30,000 last year.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'A salary figure is a single amount, not individual countable units. Use "less than $30,000."',
  },
  {
    id: 'fl-035',
    category: 'fewer-less',
    question: 'I have ___ reasons to complain now.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Reasons" is countable. One reason, two reasons. Use "fewer."',
  },
  {
    id: 'fl-036',
    category: 'fewer-less',
    question: 'The doctor recommended ___ salt in his diet.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Salt" is uncountable — a mass noun. Use "less."',
  },
  {
    id: 'fl-037',
    category: 'fewer-less',
    question: 'This semester I\'m taking ___ classes.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Classes" is countable. One class, two classes. Use "fewer."',
  },
  {
    id: 'fl-038',
    category: 'fewer-less',
    question: 'The baby is ___ than a year old.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: 'Age expressed as a continuous measurement takes "less." "Less than a year old" treats the age as a span.',
  },
  {
    id: 'fl-039',
    category: 'fewer-less',
    question: 'There was ___ traffic on the highway this morning.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Traffic" is uncountable. You cannot say "one traffic, two traffics." Use "less."',
  },
  {
    id: 'fl-040',
    category: 'fewer-less',
    question: 'She has ___ children than her sister.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Children" is countable. One child, two children. Use "fewer."',
  },
  {
    id: 'fl-041',
    category: 'fewer-less',
    question: 'He showed ___ enthusiasm than we expected.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Enthusiasm" is uncountable — an abstract quality. Use "less."',
  },
  {
    id: 'fl-042',
    category: 'fewer-less',
    question: '___ than three days remain before the deadline.',
    options: ['Fewer', 'Less'],
    correct: 'Fewer',
    explanation: 'Here "three days" refers to countable individual days remaining (day 1, day 2). When emphasizing discrete units, "fewer" is correct.',
  },
  {
    id: 'fl-043',
    category: 'fewer-less',
    question: 'The project requires ___ resources than initially planned.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Resources" is countable in this context (individual items, people, tools). Use "fewer."',
  },
  {
    id: 'fl-044',
    category: 'fewer-less',
    question: 'Add ___ garlic next time — the flavor was too strong.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Garlic" as a substance is uncountable. Use "less." (If you meant individual cloves: "fewer cloves of garlic.")',
  },
  {
    id: 'fl-045',
    category: 'fewer-less',
    question: 'The beach had ___ visitors in October than in July.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Visitors" is countable. One visitor, two visitors. Use "fewer."',
  },
  {
    id: 'fl-046',
    category: 'fewer-less',
    question: 'The team scored ___ goals this season.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Goals" is countable. You can count individual goals. Use "fewer."',
  },
  {
    id: 'fl-047',
    category: 'fewer-less',
    question: 'She paid ___ attention in class than usual.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Attention" is uncountable — it is measured in degree, not in discrete units. Use "less."',
  },
  {
    id: 'fl-048',
    category: 'fewer-less',
    question: 'The flight is ___ than two hours long.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Two hours" as a duration is a single span of time. Use "less." Compare "fewer than two hours of meetings" (countable individual hours).',
  },
  {
    id: 'fl-049',
    category: 'fewer-less',
    question: 'He owns ___ properties than his business partner.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Properties" is countable. One property, two properties. Use "fewer."',
  },
  {
    id: 'fl-050',
    category: 'fewer-less',
    question: 'The stew needs ___ liquid — it\'s too watery.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Liquid" is uncountable — a mass noun. Use "less."',
  },
  {
    id: 'fl-051',
    category: 'fewer-less',
    question: 'No ___ than a dozen complaints were filed.',
    options: ['fewer', 'less'],
    correct: 'fewer',
    explanation: '"Complaints" is countable. "No fewer than" is correct with countable nouns to mean "at least."',
  },
  {
    id: 'fl-052',
    category: 'fewer-less',
    question: 'The school has ___ funding this year.',
    options: ['fewer', 'less'],
    correct: 'less',
    explanation: '"Funding" is uncountable. It represents money/support as a mass concept. Use "less."',
  },

  // ============================================================
  // AFFECT / EFFECT
  // ============================================================
  {
    id: 'ae-001',
    category: 'affect-effect',
    question: 'The weather will ___ our travel plans.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" is a verb meaning to influence or have an impact on. The weather will influence our plans.',
  },
  {
    id: 'ae-002',
    category: 'affect-effect',
    question: 'The new law had a significant ___ on small businesses.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" is a noun meaning result or consequence. "A significant effect" — note the article "a" signaling a noun.',
  },
  {
    id: 'ae-003',
    category: 'affect-effect',
    question: 'How did the news ___ her mood?',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" is the verb meaning to influence. The news influenced her mood.',
  },
  {
    id: 'ae-004',
    category: 'affect-effect',
    question: 'The side ___ of the medication include drowsiness.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Effects" is a noun meaning results or consequences. "Side effects" is a standard compound noun.',
  },
  {
    id: 'ae-005',
    category: 'affect-effect',
    question: 'Smoking ___ your health in numerous ways.',
    options: ['affects', 'effects'],
    correct: 'affects',
    explanation: '"Affects" is a verb meaning influences. Smoking influences your health.',
  },
  {
    id: 'ae-006',
    category: 'affect-effect',
    question: 'The CEO wants to ___ real change in the company.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" can be a verb meaning to bring about or cause. "Effect change" means to make change happen. This is different from "affect change" (to influence existing change).',
  },
  {
    id: 'ae-007',
    category: 'affect-effect',
    question: 'The drought ___ crop yields across the region.',
    options: ['affected', 'effected'],
    correct: 'affected',
    explanation: '"Affected" (verb) means influenced or impacted. The drought impacted crop yields.',
  },
  {
    id: 'ae-008',
    category: 'affect-effect',
    question: 'The ___ of sleep deprivation are well documented.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Effects" (noun) means results or consequences. "The effects of..." is a very common construction.',
  },
  {
    id: 'ae-009',
    category: 'affect-effect',
    question: 'The storm did not ___ our neighborhood.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to impact. The storm did not impact our neighborhood.',
  },
  {
    id: 'ae-010',
    category: 'affect-effect',
    question: 'The medication had no ___ on her symptoms.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" (noun) means result. "Had no effect" — the noun follows "no" and describes the result.',
  },
  {
    id: 'ae-011',
    category: 'affect-effect',
    question: 'The protesters hoped to ___ a change in policy.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" as a verb means to bring about. "Effect a change" = cause a change to happen. This is the rarer verb usage.',
  },
  {
    id: 'ae-012',
    category: 'affect-effect',
    question: 'His flat ___ made it hard to tell if he was joking.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" as a noun (rare) is a psychology term meaning outward emotional expression. "Flat affect" means showing little emotion. This is the rare noun usage.',
  },
  {
    id: 'ae-013',
    category: 'affect-effect',
    question: 'The ___ areas were evacuated immediately.',
    options: ['affected', 'effected'],
    correct: 'affected',
    explanation: '"Affected" as an adjective means impacted or influenced. The impacted areas were evacuated.',
  },
  {
    id: 'ae-014',
    category: 'affect-effect',
    question: 'Will the construction ___ my commute?',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to influence or impact. Will the construction influence your commute?',
  },
  {
    id: 'ae-015',
    category: 'affect-effect',
    question: 'The greenhouse ___ is warming the planet.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Greenhouse effect" is a noun. An effect is a phenomenon or result. It is a thing (noun), not an action (verb).',
  },
  {
    id: 'ae-016',
    category: 'affect-effect',
    question: 'Your attitude ___ everyone around you.',
    options: ['affects', 'effects'],
    correct: 'affects',
    explanation: '"Affects" (verb) means influences. Your attitude influences people.',
  },
  {
    id: 'ae-017',
    category: 'affect-effect',
    question: 'The special ___ in the movie were stunning.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Special effects" is a noun phrase. Effects are the visual/audio results produced. A thing, not an action.',
  },
  {
    id: 'ae-018',
    category: 'affect-effect',
    question: 'She was deeply ___ by the documentary.',
    options: ['affected', 'effected'],
    correct: 'affected',
    explanation: '"Affected" means emotionally impacted. She was moved/influenced by the documentary.',
  },
  {
    id: 'ae-019',
    category: 'affect-effect',
    question: 'The new regulations will take ___ next month.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Take effect" is an idiomatic expression meaning to become active or operative. "Effect" is a noun here.',
  },
  {
    id: 'ae-020',
    category: 'affect-effect',
    question: 'Inflation ___ consumer purchasing power.',
    options: ['affects', 'effects'],
    correct: 'affects',
    explanation: '"Affects" (verb) means influences. Inflation influences purchasing power.',
  },
  {
    id: 'ae-021',
    category: 'affect-effect',
    question: 'The long-term ___ of the policy remain unclear.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Effects" (noun) means consequences or results. "The effects remain unclear" — it is a thing being discussed.',
  },
  {
    id: 'ae-022',
    category: 'affect-effect',
    question: 'Lack of sleep can ___ your ability to concentrate.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to impair or influence. Lack of sleep influences your concentration.',
  },
  {
    id: 'ae-023',
    category: 'affect-effect',
    question: 'The charity ___ meaningful change in the community.',
    options: ['affected', 'effected'],
    correct: 'effected',
    explanation: '"Effected" (verb) means brought about or caused. The charity brought about change. This is the rare verb form of "effect."',
  },
  {
    id: 'ae-024',
    category: 'affect-effect',
    question: 'What ___ does caffeine have on the body?',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" (noun) means result or impact. "What effect does..." asks about the result or consequence.',
  },
  {
    id: 'ae-025',
    category: 'affect-effect',
    question: 'The tax increase will ___ middle-income families the most.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to impact. The increase will impact families.',
  },
  {
    id: 'ae-026',
    category: 'affect-effect',
    question: 'He gathered his personal ___ and left the office.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Personal effects" is a legal/formal term for belongings. "Effects" as a noun can mean possessions.',
  },
  {
    id: 'ae-027',
    category: 'affect-effect',
    question: 'The cold weather ___ the turnout at the outdoor event.',
    options: ['affected', 'effected'],
    correct: 'affected',
    explanation: '"Affected" (verb) means influenced. The cold weather influenced the turnout.',
  },
  {
    id: 'ae-028',
    category: 'affect-effect',
    question: 'To ___ lasting change, we must address root causes.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" as a verb means to bring about. "Effect lasting change" = cause lasting change to happen.',
  },
  {
    id: 'ae-029',
    category: 'affect-effect',
    question: 'The patient displayed a blunted ___.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (noun, pronounced AF-ect) is a clinical psychology term for emotional expression. "Blunted affect" means diminished outward emotion.',
  },
  {
    id: 'ae-030',
    category: 'affect-effect',
    question: 'Rising sea levels ___ coastal communities worldwide.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to impact. Rising levels impact coastal communities.',
  },
  {
    id: 'ae-031',
    category: 'affect-effect',
    question: 'The butterfly ___ describes how small changes can have large consequences.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Butterfly effect" is a noun — a named phenomenon. An effect is a thing/concept.',
  },
  {
    id: 'ae-032',
    category: 'affect-effect',
    question: 'How will the merger ___ our department?',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to influence. How will it influence our department?',
  },
  {
    id: 'ae-033',
    category: 'affect-effect',
    question: 'The cumulative ___ of years of neglect was evident.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" (noun) means result. "The cumulative effect" — the noun follows an adjective and article.',
  },
  {
    id: 'ae-034',
    category: 'affect-effect',
    question: 'Nothing you say will ___ my decision.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to change or influence. Nothing will change my decision.',
  },
  {
    id: 'ae-035',
    category: 'affect-effect',
    question: 'The sound ___ in the concert hall were incredible.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Sound effects" is a noun compound. Effects are produced results — things, not actions.',
  },
  {
    id: 'ae-036',
    category: 'affect-effect',
    question: 'Stress negatively ___ the immune system.',
    options: ['affects', 'effects'],
    correct: 'affects',
    explanation: '"Affects" (verb) means influences or impacts. Stress impacts the immune system.',
  },
  {
    id: 'ae-037',
    category: 'affect-effect',
    question: 'The new mayor ___ several reforms during her first year.',
    options: ['affected', 'effected'],
    correct: 'effected',
    explanation: '"Effected" (verb) means brought about or implemented. She brought reforms into existence. She did not merely influence them — she made them happen.',
  },
  {
    id: 'ae-038',
    category: 'affect-effect',
    question: 'The ripple ___ of the decision spread throughout the organization.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Ripple effect" is a noun phrase meaning cascading consequences. An effect is a result.',
  },
  {
    id: 'ae-039',
    category: 'affect-effect',
    question: 'Does the time change ___ your sleep schedule?',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to disrupt or influence. Does it influence your sleep?',
  },
  {
    id: 'ae-040',
    category: 'affect-effect',
    question: 'The ___ of gravity on the body are measurable.',
    options: ['affects', 'effects'],
    correct: 'effects',
    explanation: '"Effects" (noun) means consequences or results. "The effects of gravity" are measurable things.',
  },
  {
    id: 'ae-041',
    category: 'affect-effect',
    question: 'Her promotion will ___ the team dynamics.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to alter or influence. The promotion will influence team dynamics.',
  },
  {
    id: 'ae-042',
    category: 'affect-effect',
    question: 'The law goes into ___ on January 1st.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Goes into effect" is an idiomatic phrase meaning becomes operative. "Effect" is a noun here.',
  },
  {
    id: 'ae-043',
    category: 'affect-effect',
    question: 'Pollution ___ air quality in urban areas.',
    options: ['affects', 'effects'],
    correct: 'affects',
    explanation: '"Affects" (verb) means degrades or influences. Pollution influences air quality.',
  },
  {
    id: 'ae-044',
    category: 'affect-effect',
    question: 'The domino ___ caused a chain of failures.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Domino effect" is a noun. It names a type of cascading consequence.',
  },
  {
    id: 'ae-045',
    category: 'affect-effect',
    question: 'The scandal could ___ his chances of reelection.',
    options: ['affect', 'effect'],
    correct: 'affect',
    explanation: '"Affect" (verb) means to harm or influence. The scandal could damage his chances.',
  },
  {
    id: 'ae-046',
    category: 'affect-effect',
    question: 'The manager was able to ___ a compromise between the two teams.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" as a verb means to bring about. The manager brought about a compromise — she made it happen.',
  },
  {
    id: 'ae-047',
    category: 'affect-effect',
    question: 'Climate change ___ weather patterns globally.',
    options: ['affects', 'effects'],
    correct: 'affects',
    explanation: '"Affects" (verb) means alters or influences. Climate change influences weather patterns.',
  },
  {
    id: 'ae-048',
    category: 'affect-effect',
    question: 'In ___, the policy does very little.',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"In effect" is an adverbial phrase meaning "in practice" or "essentially." "Effect" is a noun.',
  },
  {
    id: 'ae-049',
    category: 'affect-effect',
    question: 'The tragedy ___ the entire community.',
    options: ['affected', 'effected'],
    correct: 'affected',
    explanation: '"Affected" (verb) means impacted emotionally. The tragedy had an impact on the community.',
  },
  {
    id: 'ae-050',
    category: 'affect-effect',
    question: 'What ___ will the budget cuts have on education?',
    options: ['affect', 'effect'],
    correct: 'effect',
    explanation: '"Effect" (noun) means consequence. "What effect will..." asks about the result.',
  },
  {
    id: 'ae-051',
    category: 'affect-effect',
    question: 'The ___ communities received emergency aid.',
    options: ['affected', 'effected'],
    correct: 'affected',
    explanation: '"Affected" as an adjective means impacted. The impacted communities received aid.',
  },
  {
    id: 'ae-052',
    category: 'affect-effect',
    question: 'The diplomats ___ a ceasefire after weeks of negotiation.',
    options: ['affected', 'effected'],
    correct: 'effected',
    explanation: '"Effected" (verb) means brought about. The diplomats brought about a ceasefire — they made it happen.',
  },

  // ============================================================
  // SUBJUNCTIVE
  // ============================================================
  {
    id: 'sub-001',
    category: 'subjunctive',
    question: 'If I ___ you, I would apologize.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'The subjunctive "were" is used in hypothetical "if" clauses contrary to fact. You are not the other person, so use "If I were."',
  },
  {
    id: 'sub-002',
    category: 'subjunctive',
    question: 'I suggest that he ___ the report before Friday.',
    options: ['finishes', 'finish'],
    correct: 'finish',
    explanation: 'After verbs of suggestion, demand, or recommendation, the subjunctive uses the base form of the verb (no -s, no -ed): "suggest that he finish."',
  },
  {
    id: 'sub-003',
    category: 'subjunctive',
    question: 'It is essential that she ___ on time.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: 'After "It is essential that," the subjunctive requires the base form "be" regardless of the subject: "that she be," "that he be."',
  },
  {
    id: 'sub-004',
    category: 'subjunctive',
    question: 'She wishes she ___ taller.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"Wish" expresses a desire contrary to reality. Since she is not taller, the subjunctive "were" is used.',
  },
  {
    id: 'sub-005',
    category: 'subjunctive',
    question: 'The doctor recommended that the patient ___ more water.',
    options: ['drinks', 'drink'],
    correct: 'drink',
    explanation: '"Recommended that" triggers the subjunctive. Use the base form: "that the patient drink," not "drinks."',
  },
  {
    id: 'sub-006',
    category: 'subjunctive',
    question: 'If he ___ here right now, he would know what to do.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'This is a hypothetical contrary to fact — he is not here. The subjunctive "were" is correct for all persons in such clauses.',
  },
  {
    id: 'sub-007',
    category: 'subjunctive',
    question: 'The board demanded that the CEO ___.',
    options: ['resigns', 'resign'],
    correct: 'resign',
    explanation: '"Demanded that" triggers the subjunctive. Use the base form "resign," not "resigns."',
  },
  {
    id: 'sub-008',
    category: 'subjunctive',
    question: 'I wish it ___ raining.',
    options: ["wasn't", "weren't"],
    correct: "weren't",
    explanation: '"Wish" triggers the subjunctive for situations contrary to fact. It is raining, but you wish it were not. Use "weren\'t."',
  },
  {
    id: 'sub-009',
    category: 'subjunctive',
    question: 'It is important that every student ___ the exam.',
    options: ['takes', 'take'],
    correct: 'take',
    explanation: '"It is important that" triggers the subjunctive. Use the base form "take" regardless of the subject.',
  },
  {
    id: 'sub-010',
    category: 'subjunctive',
    question: 'If the sun ___ to disappear, life on Earth would end.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'A hypothetical contrary to fact (the sun is not disappearing) takes the subjunctive "were."',
  },
  {
    id: 'sub-011',
    category: 'subjunctive',
    question: 'She insisted that he ___ an apology.',
    options: ['makes', 'make'],
    correct: 'make',
    explanation: '"Insisted that" triggers the subjunctive. Base form "make" is required, not "makes."',
  },
  {
    id: 'sub-012',
    category: 'subjunctive',
    question: 'He acts as if he ___ the boss.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"As if" introduces a hypothetical situation. He is not actually the boss, so the subjunctive "were" applies.',
  },
  {
    id: 'sub-013',
    category: 'subjunctive',
    question: 'The professor requires that each paper ___ submitted on time.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"Requires that" triggers the subjunctive. Use "be" as the base form, not "is."',
  },
  {
    id: 'sub-014',
    category: 'subjunctive',
    question: 'I wish I ___ more time to travel.',
    options: ['have', 'had'],
    correct: 'had',
    explanation: '"Wish" for present contrary-to-fact situations uses the past subjunctive. "Had" expresses the unreal present — you do not have more time.',
  },
  {
    id: 'sub-015',
    category: 'subjunctive',
    question: 'It is crucial that the bridge ___ inspected immediately.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"It is crucial that" triggers the subjunctive. "Be inspected" uses the base form "be."',
  },
  {
    id: 'sub-016',
    category: 'subjunctive',
    question: 'If I ___ rich, I would travel the world.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'A condition contrary to fact — you are not rich. The subjunctive requires "were" for all persons.',
  },
  {
    id: 'sub-017',
    category: 'subjunctive',
    question: 'The committee proposed that the meeting ___ postponed.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"Proposed that" triggers the subjunctive. Use the base form "be," not the indicative "is."',
  },
  {
    id: 'sub-018',
    category: 'subjunctive',
    question: 'She looked at me as though I ___ crazy.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"As though" introduces a hypothetical — you are not actually crazy. Use the subjunctive "were."',
  },
  {
    id: 'sub-019',
    category: 'subjunctive',
    question: 'It is vital that the information ___ kept confidential.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"It is vital that" triggers the subjunctive. Use "be kept," the base form.',
  },
  {
    id: 'sub-020',
    category: 'subjunctive',
    question: 'I wish he ___ so stubborn.',
    options: ["wasn't", "weren't"],
    correct: "weren't",
    explanation: '"Wish" triggers the subjunctive. He is stubborn, but you wish he were not. Use "weren\'t."',
  },
  {
    id: 'sub-021',
    category: 'subjunctive',
    question: 'The judge ordered that the defendant ___ released on bail.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"Ordered that" triggers the subjunctive. Use "be released," the base form.',
  },
  {
    id: 'sub-022',
    category: 'subjunctive',
    question: 'If this ___ a dream, I wouldn\'t want to wake up.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'Hypothetical contrary to fact — this may or may not be a dream. The subjunctive "were" is correct.',
  },
  {
    id: 'sub-023',
    category: 'subjunctive',
    question: 'The regulations stipulate that each employee ___ a background check.',
    options: ['undergoes', 'undergo'],
    correct: 'undergo',
    explanation: '"Stipulate that" triggers the subjunctive. Use the base form "undergo," not "undergoes."',
  },
  {
    id: 'sub-024',
    category: 'subjunctive',
    question: 'Would that it ___ so simple.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"Would that" is a formal expression of wish, requiring the subjunctive "were." It means "I wish it were so simple."',
  },
  {
    id: 'sub-025',
    category: 'subjunctive',
    question: 'She moved that the minutes ___ approved.',
    options: ['are', 'be'],
    correct: 'be',
    explanation: '"Moved that" (in parliamentary procedure) triggers the subjunctive. "Be approved" uses the base form.',
  },
  {
    id: 'sub-026',
    category: 'subjunctive',
    question: 'If the economy ___ to collapse, millions would suffer.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'A hypothetical future scenario contrary to expected reality uses the subjunctive "were."',
  },
  {
    id: 'sub-027',
    category: 'subjunctive',
    question: 'I recommend that she ___ a second opinion.',
    options: ['gets', 'get'],
    correct: 'get',
    explanation: '"Recommend that" triggers the subjunctive. Use the base form "get," not "gets."',
  },
  {
    id: 'sub-028',
    category: 'subjunctive',
    question: 'He talks as if he ___ an expert on the subject.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"As if" introduces a hypothetical — he is not actually an expert. The subjunctive "were" applies.',
  },
  {
    id: 'sub-029',
    category: 'subjunctive',
    question: 'It is imperative that the shipment ___ by Friday.',
    options: ['arrives', 'arrive'],
    correct: 'arrive',
    explanation: '"It is imperative that" triggers the subjunctive. Use the base form "arrive."',
  },
  {
    id: 'sub-030',
    category: 'subjunctive',
    question: 'I wish I ___ studied harder in college.',
    options: ['have', 'had'],
    correct: 'had',
    explanation: '"Wish" for past contrary-to-fact uses the past perfect subjunctive. "Had studied" expresses regret about something that did not happen.',
  },
  {
    id: 'sub-031',
    category: 'subjunctive',
    question: 'The contract requires that the work ___ completed within 90 days.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"Requires that" triggers the subjunctive. Use the base form "be completed."',
  },
  {
    id: 'sub-032',
    category: 'subjunctive',
    question: 'If she ___ to ask me, I would help her.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'Hypothetical — she has not asked. "Were to ask" is the subjunctive form expressing an unlikely future possibility.',
  },
  {
    id: 'sub-033',
    category: 'subjunctive',
    question: 'The teacher asked that students ___ their phones off during class.',
    options: ['turn', 'turned'],
    correct: 'turn',
    explanation: '"Asked that" triggers the subjunctive. Use the base form "turn," not the past tense "turned."',
  },
  {
    id: 'sub-034',
    category: 'subjunctive',
    question: 'She looked as if she ___ about to cry.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"As if" with a hypothetical situation requires the subjunctive. She may or may not have been about to cry — the speaker presents it as uncertain.',
  },
  {
    id: 'sub-035',
    category: 'subjunctive',
    question: 'It is necessary that every member ___ present at the vote.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"It is necessary that" triggers the subjunctive. Use "be," not "is."',
  },
  {
    id: 'sub-036',
    category: 'subjunctive',
    question: 'I wish the noise ___ stop.',
    options: ['will', 'would'],
    correct: 'would',
    explanation: '"Wish" about a present/future annoyance uses "would" + base verb. "I wish the noise would stop" expresses frustration with an ongoing situation.',
  },
  {
    id: 'sub-037',
    category: 'subjunctive',
    question: 'The director insisted that the actor ___ the scene again.',
    options: ['rehearses', 'rehearse'],
    correct: 'rehearse',
    explanation: '"Insisted that" triggers the subjunctive. Use the base form "rehearse."',
  },
  {
    id: 'sub-038',
    category: 'subjunctive',
    question: 'If I ___ in your shoes, I would take the job.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'You are not in the other person\'s shoes — this is contrary to fact. The subjunctive "were" is required.',
  },
  {
    id: 'sub-039',
    category: 'subjunctive',
    question: 'The policy mandates that each applicant ___ a medical exam.',
    options: ['completes', 'complete'],
    correct: 'complete',
    explanation: '"Mandates that" triggers the subjunctive. Use the base form "complete."',
  },
  {
    id: 'sub-040',
    category: 'subjunctive',
    question: 'He speaks about the project as though it ___ already finished.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"As though" introduces a hypothetical — the project is not finished. Use the subjunctive "were."',
  },
  {
    id: 'sub-041',
    category: 'subjunctive',
    question: 'It is desirable that the candidate ___ bilingual.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"It is desirable that" triggers the subjunctive. Use the base form "be."',
  },
  {
    id: 'sub-042',
    category: 'subjunctive',
    question: 'I wish I ___ able to attend the ceremony.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: 'You are not able to attend — a condition contrary to fact. "Wish" triggers the subjunctive "were."',
  },
  {
    id: 'sub-043',
    category: 'subjunctive',
    question: 'The lawyer requested that the evidence ___ submitted before trial.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"Requested that" triggers the subjunctive. Use "be submitted," the base form.',
  },
  {
    id: 'sub-044',
    category: 'subjunctive',
    question: 'If it ___ not for your help, I would have failed.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"If it were not for" is a fixed subjunctive expression meaning "without." It describes a hypothetical contrary to fact.',
  },
  {
    id: 'sub-045',
    category: 'subjunctive',
    question: 'They urged that the government ___ action immediately.',
    options: ['takes', 'take'],
    correct: 'take',
    explanation: '"Urged that" triggers the subjunctive. Use the base form "take."',
  },
  {
    id: 'sub-046',
    category: 'subjunctive',
    question: 'She treats him as if he ___ a child.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"As if" with a condition contrary to fact. He is not a child. Use the subjunctive "were."',
  },
  {
    id: 'sub-047',
    category: 'subjunctive',
    question: 'It is advisable that she ___ before making a decision.',
    options: ['waits', 'wait'],
    correct: 'wait',
    explanation: '"It is advisable that" triggers the subjunctive. Use the base form "wait."',
  },
  {
    id: 'sub-048',
    category: 'subjunctive',
    question: 'If only the weather ___ better for the wedding.',
    options: ['was', 'were'],
    correct: 'were',
    explanation: '"If only" expresses a wish contrary to fact (the weather is not better). Use the subjunctive "were."',
  },
  {
    id: 'sub-049',
    category: 'subjunctive',
    question: 'The company demands that every employee ___ a nondisclosure agreement.',
    options: ['signs', 'sign'],
    correct: 'sign',
    explanation: '"Demands that" triggers the subjunctive. Use the base form "sign."',
  },
  {
    id: 'sub-050',
    category: 'subjunctive',
    question: 'I would rather she ___ the truth.',
    options: ['tells', 'told'],
    correct: 'told',
    explanation: '"Would rather" + different subject uses the past subjunctive. "I would rather she told the truth" — the past form expresses a present wish about someone else\'s action.',
  },
  {
    id: 'sub-051',
    category: 'subjunctive',
    question: 'Far ___ it from me to criticize your choices.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"Far be it from me" is a fixed subjunctive expression. The base form "be" is used in this idiomatic construction.',
  },
  {
    id: 'sub-052',
    category: 'subjunctive',
    question: 'It is recommended that the building ___ evacuated during the drill.',
    options: ['is', 'be'],
    correct: 'be',
    explanation: '"It is recommended that" triggers the subjunctive. Use "be evacuated," the base form.',
  },
];
