export interface QuickFireQuestion {
  id: string;
  type: 'grammar' | 'transition' | 'edge-case' | 'analogy' | 'hedge';
  question: string;
  options: string[];
  correct: string;
  explanation: string;
}

export const quickFireQuestions: QuickFireQuestion[] = [
  // Grammar questions
  { id: 'qf-1', type: 'grammar', question: "She's ___ honest person.", options: ['a', 'an'], correct: 'an', explanation: "'Honest' starts with a silent H, so use 'an'." },
  { id: 'qf-2', type: 'grammar', question: "There are ___ people here than yesterday.", options: ['less', 'fewer'], correct: 'fewer', explanation: "'People' is countable, so use 'fewer'." },
  { id: 'qf-3', type: 'grammar', question: "The news will ___ everyone.", options: ['affect', 'effect'], correct: 'affect', explanation: "'Affect' is the verb meaning to influence." },
  { id: 'qf-4', type: 'grammar', question: "To ___ did you give it?", options: ['who', 'whom'], correct: 'whom', explanation: "'Whom' is the object of the preposition 'to'." },
  { id: 'qf-5', type: 'grammar', question: "If I ___ you, I'd take the deal.", options: ['was', 'were'], correct: 'were', explanation: "Subjunctive mood: 'If I were' for hypotheticals." },
  { id: 'qf-6', type: 'grammar', question: "Please ___ the book on the table.", options: ['lay', 'lie'], correct: 'lay', explanation: "'Lay' takes a direct object (the book)." },
  { id: 'qf-7', type: 'grammar', question: "I need ___ information.", options: ['less', 'fewer'], correct: 'less', explanation: "'Information' is uncountable, so use 'less'." },
  { id: 'qf-8', type: 'grammar', question: "___ going to the party?", options: ['Whose', "Who's"], correct: "Who's", explanation: "'Who's' = 'who is'. 'Whose' is possessive." },
  { id: 'qf-9', type: 'grammar', question: "The ___ of the policy was immediate.", options: ['affect', 'effect'], correct: 'effect', explanation: "'Effect' is the noun meaning result." },
  { id: 'qf-10', type: 'grammar', question: "___ is responsible for this?", options: ['Who', 'Whom'], correct: 'Who', explanation: "'Who' is the subject of the verb 'is'." },
  { id: 'qf-11', type: 'grammar', question: "He ___ down for a nap yesterday.", options: ['laid', 'lay'], correct: 'lay', explanation: "'Lay' is the past tense of 'lie' (to recline)." },
  { id: 'qf-12', type: 'grammar', question: "I wish I ___ taller.", options: ['was', 'were'], correct: 'were', explanation: "Subjunctive mood: 'I wish I were' for unreal conditions." },
  { id: 'qf-13', type: 'grammar', question: "This is ___ unique opportunity.", options: ['a', 'an'], correct: 'a', explanation: "'Unique' starts with a 'yoo' sound (consonant), so use 'a'." },
  { id: 'qf-14', type: 'grammar', question: "We have ___ than 10 minutes left.", options: ['less', 'fewer'], correct: 'less', explanation: "Time is treated as uncountable, so use 'less'." },
  { id: 'qf-15', type: 'grammar', question: "The manager ___ to ___ change.", options: ['wanted / affect', 'wanted / effect'], correct: 'wanted / effect', explanation: "'Effect change' means to bring about change (verb usage of 'effect')." },

  // Transition questions
  { id: 'qf-16', type: 'transition', question: "I see your point. ___, I think there's a flaw in that logic.", options: ['That said', 'On top of that', 'Put simply', 'The bottom line is'], correct: 'That said', explanation: "'That said' is a countering transition — acknowledges then pivots." },
  { id: 'qf-17', type: 'transition', question: "Remote work saves commute time. ___, it reduces office costs.", options: ['On the other hand', 'On top of that', 'In other words', 'The point is'], correct: 'On top of that', explanation: "'On top of that' builds on the previous point." },
  { id: 'qf-18', type: 'transition', question: "We need to act fast. ___, we can't afford another delay.", options: ['Put simply', 'That said', 'Here\'s the thing', 'The bottom line is'], correct: 'The bottom line is', explanation: "'The bottom line is' concludes and summarizes." },
  { id: 'qf-19', type: 'transition', question: "That sounds complicated. ___, it's just supply and demand.", options: ['Put simply', 'That said', 'Beyond that', 'Look'], correct: 'Put simply', explanation: "'Put simply' is a clarifying transition." },
  { id: 'qf-20', type: 'transition', question: "___, I think we should step back and consider the data.", options: ['Look', 'In other words', 'Not only that', 'The bottom line is'], correct: 'Look', explanation: "'Look' is a buying-time transition that resets attention." },
  { id: 'qf-21', type: 'transition', question: "The plan saves money. ___, it saves time.", options: ['Not only that, but', 'However', 'In other words', 'The way I see it'], correct: 'Not only that, but', explanation: "'Not only that, but' builds on the previous point." },
  { id: 'qf-22', type: 'transition', question: "You say it's risky. ___, the real risk is doing nothing.", options: ["Here's the problem with that", 'On top of that', 'Put simply', 'And here\'s the thing'], correct: "Here's the problem with that", explanation: "This counters the opponent's framing." },
  { id: 'qf-23', type: 'transition', question: "We've discussed the pros. ___, what does this actually mean for our team?", options: ['So the question becomes', 'That said', 'Beyond that', 'Look'], correct: 'So the question becomes', explanation: "'So the question becomes' is a concluding transition that pivots to action." },
  { id: 'qf-24', type: 'transition', question: "I'm not against change. ___, this specific proposal has problems.", options: ["But here's what that misses", 'On top of that', 'Let me be specific', 'The way I see it'], correct: 'Let me be specific', explanation: "'Let me be specific' is a clarifying transition." },
  { id: 'qf-25', type: 'transition', question: "___, there are three reasons this won't work.", options: ['The way I see it', 'In other words', 'Beyond that', 'What this means is'], correct: 'The way I see it', explanation: "'The way I see it' is a buying-time phrase that frames your position." },

  // Edge case questions
  { id: 'qf-26', type: 'edge-case', question: "Policy: 'Free college for all.' What's the unintended consequence?",
    options: ['Everyone gets educated', 'Trade schools lose enrollment', 'Professors earn more', 'Campuses get bigger'],
    correct: 'Trade schools lose enrollment', explanation: "Free college devalues alternative paths and could create a degree arms race." },
  { id: 'qf-27', type: 'edge-case', question: "Policy: 'Raise minimum wage to $20/hr.' Edge case?",
    options: ['Workers are happier', 'Small businesses automate or close', 'Inflation disappears', 'Everyone gets raises'],
    correct: 'Small businesses automate or close', explanation: "Higher labor costs push automation and squeeze margins for small employers." },
  { id: 'qf-28', type: 'edge-case', question: "Policy: 'Ban plastic bags.' Unintended result?",
    options: ['Less litter', 'People buy thick reusable bags and throw them away too', 'Stores save money', 'Oil use drops'],
    correct: 'People buy thick reusable bags and throw them away too', explanation: "Thicker 'reusable' bags have a higher carbon footprint per unit if not reused many times." },
  { id: 'qf-29', type: 'edge-case', question: "Policy: 'Universal basic income.' Edge case?",
    options: ['Poverty ends', 'Landlords raise rent to capture the new income', 'Everyone starts businesses', 'Crime drops to zero'],
    correct: 'Landlords raise rent to capture the new income', explanation: "Without rent controls, UBI can be absorbed by housing cost increases." },
  { id: 'qf-30', type: 'edge-case', question: "Policy: 'Social media age verification.' Edge case?",
    options: ['Kids are safer', 'Creates a massive database of IDs vulnerable to breaches', 'Adults use it more', 'Companies make more money'],
    correct: 'Creates a massive database of IDs vulnerable to breaches', explanation: "Verification requires collecting sensitive identity data — a prime target for hackers." },
  { id: 'qf-31', type: 'edge-case', question: "Policy: 'Rent control.' Unintended consequence?",
    options: ['Rent stays low forever', 'Developers stop building new housing', 'Everyone can afford apartments', 'Landlords improve buildings'],
    correct: 'Developers stop building new housing', explanation: "If rents are capped, developers lack incentive to build, worsening housing shortage." },
  { id: 'qf-32', type: 'edge-case', question: "Policy: 'Four-day work week mandate.' Edge case?",
    options: ['Everyone is happier', 'Hourly workers lose 20% of their income', 'Productivity doubles', 'Companies hire more'],
    correct: 'Hourly workers lose 20% of their income', explanation: "Salaried workers benefit, but hourly workers may simply lose a day of pay." },
  { id: 'qf-33', type: 'edge-case', question: "Policy: 'Tax the rich at 70%.' Edge case?",
    options: ['Revenue doubles', 'Wealthy people relocate to lower-tax jurisdictions', 'Inequality disappears', 'Everyone pays less'],
    correct: 'Wealthy people relocate to lower-tax jurisdictions', explanation: "Capital is mobile. High tax rates can trigger capital flight and reduced investment." },
  { id: 'qf-34', type: 'edge-case', question: "Policy: 'Cancel student debt.' Edge case?",
    options: ['College becomes free', 'People who already paid off loans subsidize those who didn\'t', 'Future tuition drops', 'Banks lose money'],
    correct: "People who already paid off loans subsidize those who didn't", explanation: "Creates moral hazard and penalizes fiscal responsibility." },
  { id: 'qf-35', type: 'edge-case', question: "Policy: 'Ban cars from city centers.' Edge case?",
    options: ['Air is cleaner', 'Businesses in city centers lose foot traffic during transition', 'Everyone walks', 'Traffic disappears'],
    correct: 'Businesses in city centers lose foot traffic during transition', explanation: "Short-term economic disruption for businesses relying on drive-by traffic." },

  // Analogy questions
  { id: 'qf-36', type: 'analogy', question: "'Reading is like eating — you are what you consume.' Is this analogy strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both match on: input determines output, quality matters, effects are cumulative." },
  { id: 'qf-37', type: 'analogy', question: "'Running a company is like flying a plane — one person makes all the decisions.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "A pilot has full control; a CEO relies on teams, boards, and markets. The authority structure doesn't match." },
  { id: 'qf-38', type: 'analogy', question: "'Learning a language is like learning an instrument — daily practice compounds.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both require daily repetition, have plateau periods, and compound over years." },
  { id: 'qf-39', type: 'analogy', question: "'Democracy is like a marketplace — the best ideas win.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "Markets reward efficiency; democracy rewards popularity. The selection mechanism doesn't match." },
  { id: 'qf-40', type: 'analogy', question: "'Habits are like compound interest — small daily gains accumulate.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both involve small increments that grow exponentially over time. Structure matches." },
  { id: 'qf-41', type: 'analogy', question: "'The brain is like a muscle — use it or lose it.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both atrophy with disuse and strengthen with exercise (neuroplasticity)." },
  { id: 'qf-42', type: 'analogy', question: "'Government regulation is like parenting — it protects people from bad choices.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "Parents regulate children who can't consent; governments regulate adults who can. Consent structure doesn't match." },
  { id: 'qf-43', type: 'analogy', question: "'Social media is like junk food — designed to be addictive.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both are engineered for overconsumption, have diminishing returns, and harm with excess." },
  { id: 'qf-44', type: 'analogy', question: "'Startups are like babies — they need constant attention.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "Babies have involuntary needs; startups are strategic choices. The dependency structure differs." },
  { id: 'qf-45', type: 'analogy', question: "'Trust is like glass — once broken, never fully repaired.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both share the property of being hard to restore once damaged. Structural match." },

  // Hedge identification
  { id: 'qf-46', type: 'hedge', question: "Which sentence has NO hedges?",
    options: [
      'I think we should probably consider this.',
      'We should consider this.',
      'Maybe we could sort of look into this.',
      'I feel like this might be worth exploring.'
    ], correct: 'We should consider this.', explanation: "The others use hedges: 'I think', 'probably', 'maybe', 'sort of', 'I feel like', 'might'." },
  { id: 'qf-47', type: 'hedge', question: "Identify the hedge: 'I basically feel like we should just go for it.'",
    options: ['basically', 'feel like', 'just', 'All of these'], correct: 'All of these', explanation: "'Basically', 'feel like', and 'just' are all hedges weakening the statement." },
  { id: 'qf-48', type: 'hedge', question: "Which is sharper?",
    options: ['I think we should pivot.', 'We should pivot.', "I feel like we should maybe pivot.", 'We could probably pivot.'],
    correct: 'We should pivot.', explanation: "Direct, no hedges. The strongest version leads with the recommendation." },
  { id: 'qf-49', type: 'hedge', question: "What's wrong with: 'I mean, it's kind of a big deal, you know?'",
    options: ['Too many hedges and filler', 'Grammar error', 'Wrong transition', 'Too assertive'],
    correct: 'Too many hedges and filler', explanation: "'I mean', 'kind of', and 'you know' are all filler/hedges." },
  { id: 'qf-50', type: 'hedge', question: "Rewrite: 'I sort of feel like this approach isn't really working.'",
    options: ['This approach isn\'t working.', 'I sort of think this isn\'t working.', 'Maybe this isn\'t working that well.', 'This approach is somewhat ineffective.'],
    correct: "This approach isn't working.", explanation: "Removes all hedges. Direct and declarative." },
  { id: 'qf-51', type: 'hedge', question: "Which is the weakest opening?",
    options: ['Sorry, but I disagree.', 'I disagree.', 'I see it differently.', "Here's where I differ."],
    correct: 'Sorry, but I disagree.', explanation: "Apologizing for your opinion undercuts your authority before you even state your position." },
  { id: 'qf-52', type: 'hedge', question: "Spot the filler: 'So, like, the thing is, we just need to, um, figure this out.'",
    options: ['so, like, um', 'the thing is', 'just, figure', 'All filler words'],
    correct: 'so, like, um', explanation: "'So', 'like', and 'um' are classic verbal fillers." },
  { id: 'qf-53', type: 'hedge', question: "Which closing is strongest?",
    options: ["That's basically my take, I guess.", "Does that make sense?", "That's the core of it.", "I don't know, what do you think?"],
    correct: "That's the core of it.", explanation: "Lands clean without seeking validation or hedging." },

  // More grammar
  { id: 'qf-54', type: 'grammar', question: "I have ___ $10 in my wallet.", options: ['less than', 'fewer than'], correct: 'less than', explanation: "Money amounts are treated as uncountable — use 'less than'." },
  { id: 'qf-55', type: 'grammar', question: "The cat ___ on the couch all day.", options: ['laid', 'lay'], correct: 'lay', explanation: "'Lay' is past tense of 'lie' (to recline). No object needed." },
  { id: 'qf-56', type: 'grammar', question: "It is essential that he ___ present.", options: ['is', 'be'], correct: 'be', explanation: "Subjunctive mood after 'essential that' — use base form 'be'." },
  { id: 'qf-57', type: 'grammar', question: "___ house is this?", options: ['Whose', "Who's"], correct: 'Whose', explanation: "'Whose' is possessive. 'Who's' = 'who is'." },
  { id: 'qf-58', type: 'grammar', question: "The decision was made by ___ again?", options: ['who', 'whom'], correct: 'whom', explanation: "'By' is a preposition; its object requires 'whom'." },
  { id: 'qf-59', type: 'grammar', question: "She ___ the blanket over the sleeping child.", options: ['laid', 'lay'], correct: 'laid', explanation: "'Laid' is past tense of 'lay' (to place). There's a direct object (blanket)." },
  { id: 'qf-60', type: 'grammar', question: "He's ___ NBA player.", options: ['a', 'an'], correct: 'an', explanation: "'NBA' is pronounced 'en-bee-ay' — starts with a vowel sound." },

  // More transitions
  { id: 'qf-61', type: 'transition', question: "You make a fair point. ___, it ignores the economic reality.", options: ["But here's what that misses", 'On top of that', 'In other words', 'The bottom line is'], correct: "But here's what that misses", explanation: "Acknowledges then counters — a pivoting transition." },
  { id: 'qf-62', type: 'transition', question: "We saved 20% on costs last quarter. ___, customer satisfaction is up 15%.", options: ["What's more", 'However', 'Put simply', 'The point is this'], correct: "What's more", explanation: "'What's more' builds on positive momentum." },
  { id: 'qf-63', type: 'transition', question: "This plan sounds abstract. ___, here's what happens on day one.", options: ["Here's what that actually looks like", 'That said', 'Beyond that', 'At the end of the day'], correct: "Here's what that actually looks like", explanation: "This is a clarifying transition that grounds abstract ideas." },

  // More edge cases
  { id: 'qf-64', type: 'edge-case', question: "Policy: 'Open borders.' Edge case?",
    options: ['Cultural enrichment', 'Strain on public services in border regions', 'More tourism', 'Languages merge'],
    correct: 'Strain on public services in border regions', explanation: "Sudden population shifts can overwhelm local infrastructure and services." },
  { id: 'qf-65', type: 'edge-case', question: "Policy: 'Legalize all drugs.' Edge case?",
    options: ['Drug use drops', 'Pharmaceutical companies market addictive drugs directly to consumers', 'Crime disappears', 'Everyone gets treatment'],
    correct: 'Pharmaceutical companies market addictive drugs directly to consumers', explanation: "Legalization without regulation could enable predatory marketing of addictive substances." },

  // More hedges
  { id: 'qf-66', type: 'hedge', question: "Best replacement for 'I think maybe...'?",
    options: ["Here's my take.", "I guess perhaps...", "In my humble opinion...", "I sort of believe..."],
    correct: "Here's my take.", explanation: "Direct, confident, no hedging. Replaces two hedges with assertion." },
  { id: 'qf-67', type: 'hedge', question: "Best replacement for 'Does that make sense?'",
    options: ["You know?", "Right?", "That's the core of it.", "Am I being clear?"],
    correct: "That's the core of it.", explanation: "Ends with confidence instead of seeking validation." },

  // More analogies
  { id: 'qf-68', type: 'analogy', question: "'Teaching is like gardening — you plant seeds and wait.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both involve nurturing, patience, and outcomes you can't force. Good structural match." },
  { id: 'qf-69', type: 'analogy', question: "'A team is like a family — you can't choose your members.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "You CAN choose team members through hiring. The selection mechanism doesn't match." },
  { id: 'qf-70', type: 'analogy', question: "'Reputation is like a fire — takes forever to build, seconds to destroy.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both share asymmetric build/destroy timelines. Clean structural match." },

  // Final mix
  { id: 'qf-71', type: 'grammar', question: "The ___ of the medication were severe.", options: ['affects', 'effects'], correct: 'effects', explanation: "'Effects' (noun) = results/consequences." },
  { id: 'qf-72', type: 'grammar', question: "She suggested that he ___ the project.", options: ['leads', 'lead'], correct: 'lead', explanation: "Subjunctive: 'suggest that he lead' (base form)." },
  { id: 'qf-73', type: 'hedge', question: "Strongest way to open a disagreement?",
    options: ["Well, I don't know, but...", "I see it differently.", "Sorry, I might be wrong, but...", "I mean, not to be rude, but..."],
    correct: "I see it differently.", explanation: "Confident, respectful, zero hedging." },
  { id: 'qf-74', type: 'transition', question: "We tried that approach. ___ — it failed in Q2.", options: ["Here's the thing", "On top of that", "In other words", "What's more"], correct: "Here's the thing", explanation: "'Here's the thing' is a buying-time transition that signals you're about to deliver a key point." },
  { id: 'qf-75', type: 'edge-case', question: "Policy: 'Universal healthcare.' Edge case?",
    options: ['Everyone is healthier', 'Wait times increase dramatically', 'Hospitals improve', 'Doctors earn more'],
    correct: 'Wait times increase dramatically', explanation: "Increased demand without proportional supply increase leads to longer waits." },
  { id: 'qf-76', type: 'grammar', question: "I have ___ items in my cart.", options: ['less', 'fewer'], correct: 'fewer', explanation: "'Items' is countable — use 'fewer'." },
  { id: 'qf-77', type: 'analogy', question: "'Money is like oxygen — you don't think about it until you don't have it.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Strong', explanation: "Both are invisible necessities that become urgent only in absence. Clean match." },
  { id: 'qf-78', type: 'hedge', question: "What makes this weak: 'Honestly, I just think we probably need to maybe reconsider.'",
    options: ['5 hedges in one sentence', 'Grammar error', 'Wrong transition', 'Too short'],
    correct: '5 hedges in one sentence', explanation: "'Honestly', 'just', 'think', 'probably', 'maybe' — five qualifiers destroying one sentence." },
  { id: 'qf-79', type: 'grammar', question: "___ did the committee select?", options: ['Who', 'Whom'], correct: 'Whom', explanation: "'Whom' is the object of 'select'. (The committee selected whom?)" },
  { id: 'qf-80', type: 'transition', question: "That's a nice theory. ___, it falls apart in practice.", options: ['The issue is', 'On top of that', 'Put simply', 'And here\'s the thing'], correct: 'The issue is', explanation: "'The issue is' is a countering transition." },
  { id: 'qf-81', type: 'grammar', question: "It is ___ honor to be here.", options: ['a', 'an'], correct: 'an', explanation: "'Honor' has a silent H — starts with vowel sound." },
  { id: 'qf-82', type: 'grammar', question: "The dog has ___ there all day.", options: ['laid', 'lain'], correct: 'lain', explanation: "'Lain' is the past participle of 'lie' (to recline). 'Has lain'." },
  { id: 'qf-83', type: 'edge-case', question: "Policy: 'Defund the police.' Edge case?",
    options: ['Crime drops', 'Wealthy neighborhoods hire private security, increasing inequality', 'Officers earn more', 'Courts are less busy'],
    correct: 'Wealthy neighborhoods hire private security, increasing inequality', explanation: "Reduced public safety funding privatizes security for those who can afford it." },
  { id: 'qf-84', type: 'grammar', question: "This is ___ European country.", options: ['a', 'an'], correct: 'a', explanation: "'European' starts with a 'yoo' consonant sound, so use 'a'." },
  { id: 'qf-85', type: 'analogy', question: "'Ideas are like children — you shouldn't play favorites.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "Ideas SHOULD be evaluated and prioritized. Children shouldn't. The value structure doesn't match." },
  { id: 'qf-86', type: 'grammar', question: "The weather will ___ our plans.", options: ['affect', 'effect'], correct: 'affect', explanation: "'Affect' = verb meaning to influence." },
  { id: 'qf-87', type: 'hedge', question: "Which replaces 'Umm so basically...'?",
    options: ['Put simply.', 'So basically, like...', 'Umm, the thing is...', 'I mean, basically...'],
    correct: 'Put simply.', explanation: "Clean, confident replacement for verbal filler and hedging." },
  { id: 'qf-88', type: 'grammar', question: "___ you meet will determine your path.", options: ['Whoever', 'Whomever'], correct: 'Whoever', explanation: "'Whoever' is the subject of 'you meet' — it does the meeting." },
  { id: 'qf-89', type: 'transition', question: "We cut costs. We improved quality. ___, we did it ahead of schedule.", options: ['And here\'s the thing', 'On the other hand', 'In other words', 'That said'], correct: "And here's the thing", explanation: "Builds to a climactic third point." },
  { id: 'qf-90', type: 'grammar', question: "She ___ the phone on the counter.", options: ['lay', 'laid'], correct: 'laid', explanation: "'Laid' = past tense of 'lay' (to place something). 'Phone' is the object." },
  { id: 'qf-91', type: 'edge-case', question: "Policy: 'Free school lunches for all.' Edge case?",
    options: ['Kids eat better', 'Removes the stigma from kids who need it most', 'Food waste increases', 'Schools have less money'],
    correct: 'Removes the stigma from kids who need it most', explanation: "This is actually a positive edge case — universal programs remove shame from targeted aid." },
  { id: 'qf-92', type: 'grammar', question: "He asked ___ I thought should be promoted.", options: ['who', 'whom'], correct: 'who', explanation: "'Who' is the subject of 'should be promoted', not the object of 'asked'." },
  { id: 'qf-93', type: 'hedge', question: "Rank these from weakest to strongest:",
    options: [
      "I guess we could try. → We should try. → Let's try.",
      "Let's try. → We should try. → I guess we could try.",
      "We should try. → I guess we could try. → Let's try.",
      "Let's try. → I guess we could try. → We should try."
    ],
    correct: "I guess we could try. → We should try. → Let's try.",
    explanation: "Weakest has two hedges, middle is declarative, strongest is a direct call to action."
  },
  { id: 'qf-94', type: 'grammar', question: "I need ___ one hour to finish.", options: ['less than', 'fewer than'], correct: 'less than', explanation: "Time durations use 'less than' even though hours seem countable." },
  { id: 'qf-95', type: 'analogy', question: "'Leadership is like chess — you sacrifice pieces to win.' Strong or weak?",
    options: ['Strong', 'Weak'], correct: 'Weak', explanation: "Chess pieces don't have feelings. Leaders who 'sacrifice people' are poor leaders. The human element breaks the analogy." },
  { id: 'qf-96', type: 'grammar', question: "The hen ___ an egg this morning.", options: ['laid', 'lay'], correct: 'laid', explanation: "'Laid' = past tense of 'lay' (to place/produce). The egg is the object." },
  { id: 'qf-97', type: 'transition', question: "They claim it's efficient. ___ — efficiency without effectiveness is waste.", options: ["Here's the problem with that", 'On top of that', 'Let me be specific', 'The way I see it'], correct: "Here's the problem with that", explanation: "Directly challenges the opponent's claim." },
  { id: 'qf-98', type: 'grammar', question: "If he ___ here, he'd agree with me.", options: ['was', 'were'], correct: 'were', explanation: "Subjunctive: 'If he were' for contrary-to-fact conditions." },
  { id: 'qf-99', type: 'hedge', question: "Which closing avoids seeking validation?",
    options: ["Know what I mean?", "Right?", "That's where I stand.", "Make sense?"],
    correct: "That's where I stand.", explanation: "Ends with a firm position statement, not a question seeking approval." },
  { id: 'qf-100', type: 'grammar', question: "Give the trophy to ___ wins.", options: ['whoever', 'whomever'], correct: 'whoever', explanation: "'Whoever' is the subject of 'wins'. The whole clause 'whoever wins' is the object of 'to'." },
];
