export interface SentencePair {
  id: string;
  category: 'hedging' | 'rambling' | 'passive' | 'vague' | 'wordy' | 'weak-opening';
  weak: string;
  sharp: string;
  principles: string[];
}

export const principlesList = [
  'One idea per sentence',
  'Lead with the point',
  'Cut hedges (I think, basically, probably)',
  'Short and declarative',
  'Use active voice',
  'Be specific, not vague',
  'Remove unnecessary qualifiers',
  'Strong verb choice',
] as const;

export const sentencePairs: SentencePair[] = [
  // ============================================================
  // HEDGING (20 pairs)
  // ============================================================
  {
    id: 'hedge-001',
    category: 'hedging',
    weak: 'I think we should probably maybe look into switching to a different vendor at some point.',
    sharp: 'We should switch vendors.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'hedge-002',
    category: 'hedging',
    weak: 'I feel like this might not be the best approach, but I could be wrong.',
    sharp: 'This approach has a flaw.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative', 'Be specific, not vague'],
  },
  {
    id: 'hedge-003',
    category: 'hedging',
    weak: 'I guess what I\'m trying to say is that the deadline seems a little unrealistic to me.',
    sharp: 'The deadline is unrealistic.',
    principles: ['Cut hedges (I think, basically, probably)', 'Lead with the point'],
  },
  {
    id: 'hedge-004',
    category: 'hedging',
    weak: 'It\'s sort of like, I don\'t know, I just think the design could maybe be a bit better.',
    sharp: 'The design needs work.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'hedge-005',
    category: 'hedging',
    weak: 'I\'m not sure, but I think we probably shouldn\'t launch until we\'ve done more testing or something.',
    sharp: 'We need more testing before launch.',
    principles: ['Cut hedges (I think, basically, probably)', 'Lead with the point'],
  },
  {
    id: 'hedge-006',
    category: 'hedging',
    weak: 'Basically, I kind of feel like the pricing might be a little too high for most customers, if that makes sense.',
    sharp: 'The pricing is too high for most customers.',
    principles: ['Cut hedges (I think, basically, probably)', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'hedge-007',
    category: 'hedging',
    weak: 'I mean, it\'s just my opinion, but I think we should probably consider hiring someone for that role.',
    sharp: 'We should hire for that role.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'hedge-008',
    category: 'hedging',
    weak: 'I was kind of wondering if maybe it would be possible to get an extension on this.',
    sharp: 'I need an extension.',
    principles: ['Cut hedges (I think, basically, probably)', 'Lead with the point', 'Short and declarative'],
  },
  {
    id: 'hedge-009',
    category: 'hedging',
    weak: 'I\'m not an expert or anything, but I think there might possibly be a bug in the authentication flow.',
    sharp: 'There is a bug in the authentication flow.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'hedge-010',
    category: 'hedging',
    weak: 'In my humble opinion, I think we might want to think about possibly revisiting the roadmap.',
    sharp: 'We should revisit the roadmap.',
    principles: ['Cut hedges (I think, basically, probably)', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'hedge-011',
    category: 'hedging',
    weak: 'I don\'t want to step on anyone\'s toes, but I sort of feel like this project is maybe going in the wrong direction.',
    sharp: 'This project is going in the wrong direction.',
    principles: ['Cut hedges (I think, basically, probably)', 'Lead with the point'],
  },
  {
    id: 'hedge-012',
    category: 'hedging',
    weak: 'It seems like it might be the case that our competitors are probably doing a better job with onboarding.',
    sharp: 'Our competitors have better onboarding.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative', 'Strong verb choice'],
  },
  {
    id: 'hedge-013',
    category: 'hedging',
    weak: 'I could be totally off here, but I think the numbers in the report might not be completely accurate.',
    sharp: 'The numbers in the report are wrong.',
    principles: ['Cut hedges (I think, basically, probably)', 'Be specific, not vague'],
  },
  {
    id: 'hedge-014',
    category: 'hedging',
    weak: 'Just a thought, but maybe we should possibly think about adding dark mode at some point.',
    sharp: 'We should add dark mode.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'hedge-015',
    category: 'hedging',
    weak: 'I suppose what I\'m getting at is that the meeting probably could have been an email, if I\'m being honest.',
    sharp: 'That meeting should have been an email.',
    principles: ['Cut hedges (I think, basically, probably)', 'Lead with the point'],
  },
  {
    id: 'hedge-016',
    category: 'hedging',
    weak: 'I\'m probably wrong about this, but I feel like we\'re maybe spending too much on advertising.',
    sharp: 'We are overspending on advertising.',
    principles: ['Cut hedges (I think, basically, probably)', 'Strong verb choice'],
  },
  {
    id: 'hedge-017',
    category: 'hedging',
    weak: 'You know, I was just thinking that it might be nice if we could maybe try doing standups differently.',
    sharp: 'Let\'s change how we run standups.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative', 'Strong verb choice'],
  },
  {
    id: 'hedge-018',
    category: 'hedging',
    weak: 'I don\'t know if this is the right way to put it, but I feel like our documentation is sort of lacking.',
    sharp: 'Our documentation is incomplete.',
    principles: ['Cut hedges (I think, basically, probably)', 'Be specific, not vague'],
  },
  {
    id: 'hedge-019',
    category: 'hedging',
    weak: 'This is probably a dumb question, but I was just wondering if we\'ve maybe thought about accessibility.',
    sharp: 'Have we addressed accessibility?',
    principles: ['Cut hedges (I think, basically, probably)', 'Lead with the point'],
  },
  {
    id: 'hedge-020',
    category: 'hedging',
    weak: 'I hate to be that person, but I kind of think the food at the offsite was not that great, honestly.',
    sharp: 'The offsite food was bad.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },

  // ============================================================
  // RAMBLING (18 pairs)
  // ============================================================
  {
    id: 'ramble-001',
    category: 'rambling',
    weak: 'So the thing is, I was talking to Sarah the other day, and she mentioned that their team has been having some issues with the API, and I think the issue is that the rate limits are too low, and we should probably increase them because it\'s causing problems for multiple teams now.',
    sharp: 'Multiple teams are hitting API rate limits. We need to increase them.',
    principles: ['One idea per sentence', 'Lead with the point', 'Short and declarative'],
  },
  {
    id: 'ramble-002',
    category: 'rambling',
    weak: 'I wanted to bring up something that\'s been on my mind for a while, which is that we have this process for code reviews where everyone has to approve before merging, and it takes forever, and I think it\'s really slowing us down, and other companies don\'t do it this way.',
    sharp: 'Our code review process requires too many approvals. It delays every merge. We should reduce to two reviewers.',
    principles: ['One idea per sentence', 'Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'ramble-003',
    category: 'rambling',
    weak: 'So what happened was, the deploy went out on Friday, and then over the weekend we started getting alerts, and it turns out there was a memory leak, and the on-call person didn\'t see it until Monday, and by then the service had been degraded for like two days.',
    sharp: 'Friday\'s deploy introduced a memory leak. It went undetected for two days because on-call missed the weekend alerts.',
    principles: ['One idea per sentence', 'Lead with the point'],
  },
  {
    id: 'ramble-004',
    category: 'rambling',
    weak: 'I\'ve been thinking about this a lot and talking to different people on the team, and the consensus seems to be that the new tool is actually harder to use than the old one, and it doesn\'t really save us any time, and some people are even going back to the old workflow because it\'s just faster.',
    sharp: 'The new tool is slower than the old one. Team members are reverting to the previous workflow.',
    principles: ['One idea per sentence', 'Lead with the point', 'Short and declarative'],
  },
  {
    id: 'ramble-005',
    category: 'rambling',
    weak: 'OK so for context, last quarter we tried this new marketing campaign where we did influencer partnerships, and it was kind of expensive, but the thing is we didn\'t really track the ROI properly, so now we don\'t know if it worked, and the CMO is asking for numbers.',
    sharp: 'We failed to track ROI on last quarter\'s influencer campaign. The CMO needs numbers we don\'t have.',
    principles: ['One idea per sentence', 'Lead with the point', 'Strong verb choice'],
  },
  {
    id: 'ramble-006',
    category: 'rambling',
    weak: 'The customer called in and was really upset because they had been waiting for three weeks for a response, and apparently their ticket got reassigned twice, and nobody followed up, and now they\'re threatening to cancel their enterprise contract which is worth like $200K annually.',
    sharp: 'A $200K enterprise customer is threatening to cancel. Their support ticket went unanswered for three weeks after two reassignments.',
    principles: ['Lead with the point', 'One idea per sentence', 'Be specific, not vague'],
  },
  {
    id: 'ramble-007',
    category: 'rambling',
    weak: 'So I was looking at the analytics dashboard this morning and I noticed something interesting, which is that our bounce rate has gone up significantly in the last month, and I think it might be related to the homepage redesign we did, because the timing lines up.',
    sharp: 'Bounce rate spiked last month. It correlates with the homepage redesign.',
    principles: ['One idea per sentence', 'Lead with the point', 'Short and declarative'],
  },
  {
    id: 'ramble-008',
    category: 'rambling',
    weak: 'We need to talk about the hiring situation because we posted the job listing two months ago and we\'ve only gotten a handful of qualified applicants, and the recruiter says the job description might be too demanding, and the salary range might be too low for the market.',
    sharp: 'Our job posting has attracted few qualified applicants in two months. The recruiter says we need to lower requirements or raise the salary.',
    principles: ['One idea per sentence', 'Lead with the point'],
  },
  {
    id: 'ramble-009',
    category: 'rambling',
    weak: 'This is kind of a long story, but basically we had a contractor who was working on the data pipeline, and they left suddenly, and nobody documented what they built, and now the pipeline is breaking and nobody on the team understands the code well enough to fix it.',
    sharp: 'A contractor left without documenting the data pipeline. It\'s breaking and nobody can fix it.',
    principles: ['One idea per sentence', 'Short and declarative', 'Lead with the point'],
  },
  {
    id: 'ramble-010',
    category: 'rambling',
    weak: 'I just wanted to let you know that I ran into Tom from engineering at lunch and he told me that their team is also building a notification service, which is basically the same thing our team is working on, and I think we should probably coordinate so we don\'t duplicate effort.',
    sharp: 'Engineering is building a notification service too. We\'re duplicating effort and need to coordinate.',
    principles: ['One idea per sentence', 'Lead with the point', 'Short and declarative'],
  },
  {
    id: 'ramble-011',
    category: 'rambling',
    weak: 'The thing about the quarterly planning process is that every team submits their proposals, and then leadership takes weeks to review them, and by the time they approve anything the quarter is already underway, and teams have already started working on things that might not get approved.',
    sharp: 'Quarterly planning approvals take too long. Teams start unapproved work while waiting. We need faster decisions.',
    principles: ['One idea per sentence', 'Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'ramble-012',
    category: 'rambling',
    weak: 'I was reading this article about how Netflix does their engineering culture, and it got me thinking about how we handle incident response, because I feel like we spend too much time on blameless postmortems that don\'t actually result in action items getting completed, and then the same incidents keep happening.',
    sharp: 'Our postmortems produce action items that never get completed. The same incidents keep recurring.',
    principles: ['Lead with the point', 'One idea per sentence', 'Short and declarative'],
  },
  {
    id: 'ramble-013',
    category: 'rambling',
    weak: 'Hey, so I wanted to circle back on the conversation we had last week about the budget, because I went and pulled the numbers and it turns out we\'re actually 15% over on infrastructure costs, and a big chunk of that is unused cloud resources that nobody has cleaned up.',
    sharp: 'We\'re 15% over budget on infrastructure. Unused cloud resources are the main driver.',
    principles: ['Lead with the point', 'One idea per sentence', 'Be specific, not vague'],
  },
  {
    id: 'ramble-014',
    category: 'rambling',
    weak: 'So there\'s this situation with the mobile app where users have been complaining about battery drain, and our team investigated and found that the background sync is running way too frequently, like every 30 seconds instead of every 5 minutes, and it\'s been like that since the last update.',
    sharp: 'The last update broke background sync frequency: it runs every 30 seconds instead of every 5 minutes. This is causing battery drain complaints.',
    principles: ['Lead with the point', 'One idea per sentence', 'Be specific, not vague'],
  },
  {
    id: 'ramble-015',
    category: 'rambling',
    weak: 'I know this isn\'t really my area, but I noticed that the sales team keeps promising features to customers that we haven\'t built yet, and then engineering gets pressured to rush them out, and the quality suffers, and then we end up with tech debt that slows everything else down.',
    sharp: 'Sales is promising unbuilt features to customers. Engineering rushes to deliver them, creating tech debt. We need a feature commitment policy.',
    principles: ['One idea per sentence', 'Lead with the point', 'Strong verb choice'],
  },
  {
    id: 'ramble-016',
    category: 'rambling',
    weak: 'What I\'m trying to explain is that the database migration is risky because we have 50 million rows, and if something goes wrong we could lose data, and rolling back isn\'t straightforward because the schema changes are destructive, so we need a really solid plan.',
    sharp: 'The database migration risks data loss across 50 million rows. Schema changes are destructive, making rollback impossible. We need a bulletproof plan.',
    principles: ['One idea per sentence', 'Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'ramble-017',
    category: 'rambling',
    weak: 'There\'s been some back and forth in the Slack channel about whether we should use TypeScript or Go for the new service, and people have strong opinions on both sides, and I think we just need someone to make a decision so we can move forward instead of debating endlessly.',
    sharp: 'The TypeScript vs. Go debate is stalling the new service. Someone needs to make the call.',
    principles: ['Lead with the point', 'Short and declarative', 'One idea per sentence'],
  },
  {
    id: 'ramble-018',
    category: 'rambling',
    weak: 'So the situation with the intern is that they\'re really talented and doing great work, but their internship ends in two weeks, and I think we should try to convert them to full-time, but we need headcount approval, and HR says the process takes at least a month.',
    sharp: 'Our top intern\'s contract ends in two weeks. Converting them to full-time takes a month. We need headcount approval now.',
    principles: ['One idea per sentence', 'Lead with the point', 'Be specific, not vague'],
  },

  // ============================================================
  // PASSIVE (18 pairs)
  // ============================================================
  {
    id: 'passive-001',
    category: 'passive',
    weak: 'It was decided that the project would be postponed until further notice.',
    sharp: 'Management postponed the project indefinitely.',
    principles: ['Use active voice', 'Be specific, not vague'],
  },
  {
    id: 'passive-002',
    category: 'passive',
    weak: 'The report was not completed on time due to resources being unavailable.',
    sharp: 'We missed the report deadline because we lacked resources.',
    principles: ['Use active voice', 'Be specific, not vague'],
  },
  {
    id: 'passive-003',
    category: 'passive',
    weak: 'Mistakes were made during the migration process.',
    sharp: 'The ops team made mistakes during the migration.',
    principles: ['Use active voice', 'Be specific, not vague'],
  },
  {
    id: 'passive-004',
    category: 'passive',
    weak: 'It has been suggested that the meeting frequency should be reduced.',
    sharp: 'The team wants fewer meetings.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'passive-005',
    category: 'passive',
    weak: 'The feature was shipped without proper testing being done.',
    sharp: 'We shipped the feature without testing it.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'passive-006',
    category: 'passive',
    weak: 'A decision needs to be made regarding the budget allocation for Q3.',
    sharp: 'We need to decide the Q3 budget allocation.',
    principles: ['Use active voice', 'Lead with the point'],
  },
  {
    id: 'passive-007',
    category: 'passive',
    weak: 'The customer\'s complaint was not addressed in a timely manner.',
    sharp: 'Support ignored the customer\'s complaint for two weeks.',
    principles: ['Use active voice', 'Be specific, not vague', 'Strong verb choice'],
  },
  {
    id: 'passive-008',
    category: 'passive',
    weak: 'The new policy was implemented without employees being consulted.',
    sharp: 'Leadership implemented the policy without consulting employees.',
    principles: ['Use active voice', 'Be specific, not vague'],
  },
  {
    id: 'passive-009',
    category: 'passive',
    weak: 'It is believed that the outage was caused by a configuration error.',
    sharp: 'A configuration error caused the outage.',
    principles: ['Use active voice', 'Short and declarative', 'Lead with the point'],
  },
  {
    id: 'passive-010',
    category: 'passive',
    weak: 'Your request has been received and will be processed in the order it was submitted.',
    sharp: 'We received your request and will process it in order.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'passive-011',
    category: 'passive',
    weak: 'The data was accidentally deleted by someone on the team.',
    sharp: 'A team member accidentally deleted the data.',
    principles: ['Use active voice', 'Lead with the point'],
  },
  {
    id: 'passive-012',
    category: 'passive',
    weak: 'It was determined that the root cause of the issue was a race condition that had been introduced in the last release.',
    sharp: 'The last release introduced a race condition that caused the issue.',
    principles: ['Use active voice', 'Lead with the point', 'Short and declarative'],
  },
  {
    id: 'passive-013',
    category: 'passive',
    weak: 'The proposal was reviewed and it was felt that changes should be made before it can be approved.',
    sharp: 'The review committee rejected the proposal pending changes.',
    principles: ['Use active voice', 'Strong verb choice', 'Be specific, not vague'],
  },
  {
    id: 'passive-014',
    category: 'passive',
    weak: 'The application was denied because certain requirements were not met by the applicant.',
    sharp: 'We denied the application because the applicant missed key requirements.',
    principles: ['Use active voice', 'Be specific, not vague'],
  },
  {
    id: 'passive-015',
    category: 'passive',
    weak: 'Concerns have been raised by several stakeholders about the timeline.',
    sharp: 'Several stakeholders flagged timeline concerns.',
    principles: ['Use active voice', 'Short and declarative', 'Strong verb choice'],
  },
  {
    id: 'passive-016',
    category: 'passive',
    weak: 'The server was brought down for maintenance and users were not notified in advance.',
    sharp: 'We took the server down for maintenance without notifying users.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'passive-017',
    category: 'passive',
    weak: 'An agreement was reached by both parties after the terms were renegotiated.',
    sharp: 'Both parties renegotiated and reached an agreement.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'passive-018',
    category: 'passive',
    weak: 'The test results were reviewed and it was concluded that further investigation is needed.',
    sharp: 'We reviewed the test results and found they need further investigation.',
    principles: ['Use active voice', 'One idea per sentence'],
  },

  // ============================================================
  // VAGUE (18 pairs)
  // ============================================================
  {
    id: 'vague-001',
    category: 'vague',
    weak: 'We need to improve the user experience.',
    sharp: 'We need to reduce checkout from five steps to two.',
    principles: ['Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'vague-002',
    category: 'vague',
    weak: 'The performance isn\'t great and we should make it better.',
    sharp: 'Page load takes 8 seconds. We need it under 2.',
    principles: ['Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'vague-003',
    category: 'vague',
    weak: 'We need to be more innovative as a company.',
    sharp: 'We should dedicate 20% of engineering time to experimental projects.',
    principles: ['Be specific, not vague', 'Lead with the point'],
  },
  {
    id: 'vague-004',
    category: 'vague',
    weak: 'The communication between teams could be better.',
    sharp: 'Design and engineering need a weekly sync to catch misalignment early.',
    principles: ['Be specific, not vague', 'Lead with the point'],
  },
  {
    id: 'vague-005',
    category: 'vague',
    weak: 'We should do something about employee engagement.',
    sharp: 'Employee satisfaction scores dropped 15 points. We should survey to find the root cause.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'vague-006',
    category: 'vague',
    weak: 'The project has some issues that need to be addressed.',
    sharp: 'The project is three weeks behind schedule and $40K over budget.',
    principles: ['Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'vague-007',
    category: 'vague',
    weak: 'We should leverage our synergies to drive growth.',
    sharp: 'Combining the sales and marketing databases would let us cross-sell to 10,000 untapped leads.',
    principles: ['Be specific, not vague', 'Lead with the point'],
  },
  {
    id: 'vague-008',
    category: 'vague',
    weak: 'The code quality needs improvement.',
    sharp: 'We have 342 unresolved linting errors and zero unit tests on the payments module.',
    principles: ['Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'vague-009',
    category: 'vague',
    weak: 'The customer feedback has been mixed.',
    sharp: '60% of reviews praise speed, but 80% complain about the search feature.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'vague-010',
    category: 'vague',
    weak: 'Things are going well with the new hire.',
    sharp: 'The new hire shipped two features in her first week and fixed a critical bug.',
    principles: ['Be specific, not vague', 'Strong verb choice'],
  },
  {
    id: 'vague-011',
    category: 'vague',
    weak: 'The app could use some work.',
    sharp: 'The app crashes on Android 13 devices and the login flow has a 30% drop-off rate.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'vague-012',
    category: 'vague',
    weak: 'The meeting went well overall.',
    sharp: 'The client approved the design, signed the contract, and set a June 1 launch date.',
    principles: ['Be specific, not vague', 'Lead with the point'],
  },
  {
    id: 'vague-013',
    category: 'vague',
    weak: 'We need to take our strategy to the next level.',
    sharp: 'We should enter the European market by Q3 and target 500 enterprise customers.',
    principles: ['Be specific, not vague', 'Lead with the point'],
  },
  {
    id: 'vague-014',
    category: 'vague',
    weak: 'There are concerns about security.',
    sharp: 'Our API tokens have no expiration, and we store passwords in plaintext.',
    principles: ['Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'vague-015',
    category: 'vague',
    weak: 'The dinner was nice.',
    sharp: 'The steak was cooked perfectly and the wine pairing was excellent.',
    principles: ['Be specific, not vague'],
  },
  {
    id: 'vague-016',
    category: 'vague',
    weak: 'We need to think about scalability.',
    sharp: 'Our database will hit its row limit at 10 million users. We need to shard before Q4.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'vague-017',
    category: 'vague',
    weak: 'The presentation had room for improvement.',
    sharp: 'The presentation had no data to support its claims and ran 20 minutes over time.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'vague-018',
    category: 'vague',
    weak: 'We should probably do something about technical debt.',
    sharp: 'Technical debt adds two days to every feature. We should dedicate one sprint per quarter to pay it down.',
    principles: ['Be specific, not vague', 'Cut hedges (I think, basically, probably)', 'One idea per sentence'],
  },

  // ============================================================
  // WORDY (18 pairs)
  // ============================================================
  {
    id: 'wordy-001',
    category: 'wordy',
    weak: 'At this point in time, we are currently in the process of evaluating the various different options that are available to us.',
    sharp: 'We are evaluating our options.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-002',
    category: 'wordy',
    weak: 'I am writing to you in order to inform you that your subscription is going to be expiring at the end of the current month.',
    sharp: 'Your subscription expires at month end.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },
  {
    id: 'wordy-003',
    category: 'wordy',
    weak: 'Due to the fact that we are experiencing a high volume of requests, the response time may be longer than what is normally expected.',
    sharp: 'High request volume is slowing response times.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-004',
    category: 'wordy',
    weak: 'In light of the aforementioned circumstances, it would be advisable for us to take into consideration the possibility of postponing the launch.',
    sharp: 'Given these circumstances, we should postpone the launch.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },
  {
    id: 'wordy-005',
    category: 'wordy',
    weak: 'I would like to take this opportunity to express my sincere gratitude for the hard work and dedication that each and every one of you has demonstrated.',
    sharp: 'Thank you all for your hard work.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-006',
    category: 'wordy',
    weak: 'It is absolutely essential and critically important that we make sure to complete the audit before the deadline.',
    sharp: 'We must complete the audit before the deadline.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Strong verb choice'],
  },
  {
    id: 'wordy-007',
    category: 'wordy',
    weak: 'The reason why I am reaching out to you today is because I wanted to ask you a question about the new policy that was recently put in place.',
    sharp: 'I have a question about the new policy.',
    principles: ['Short and declarative', 'Lead with the point', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-008',
    category: 'wordy',
    weak: 'We have come to the conclusion that, after careful review and thorough analysis of the situation, we should go ahead and proceed with the original plan.',
    sharp: 'After review, we will proceed with the original plan.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-009',
    category: 'wordy',
    weak: 'For all intents and purposes, the end result of this initiative is basically going to be a complete and total restructuring of the department.',
    sharp: 'This initiative will restructure the department.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Strong verb choice'],
  },
  {
    id: 'wordy-010',
    category: 'wordy',
    weak: 'I think it is worth mentioning and noting that the vast majority of our customer base tends to prefer the current version of the product over the new one.',
    sharp: 'Most customers prefer the current product version.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'wordy-011',
    category: 'wordy',
    weak: 'Please do not hesitate to reach out and contact me if you have any questions, concerns, or issues that you would like to discuss at any point.',
    sharp: 'Contact me with any questions.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-012',
    category: 'wordy',
    weak: 'In order to ensure that we are all on the same page and aligned with respect to the goals and objectives of this project, I would like to schedule a meeting.',
    sharp: 'Let\'s meet to align on project goals.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },
  {
    id: 'wordy-013',
    category: 'wordy',
    weak: 'The actual underlying root cause of the problem is the simple fact that we don\'t have enough people on the team to handle the workload.',
    sharp: 'The team is understaffed for the workload.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },
  {
    id: 'wordy-014',
    category: 'wordy',
    weak: 'What I would suggest and recommend at this particular juncture is that we take a step back and reassess and reevaluate our priorities moving forward.',
    sharp: 'We should reassess our priorities.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-015',
    category: 'wordy',
    weak: 'The reason that the deployment failed was because of the fact that the configuration file had an error in it that prevented it from being parsed correctly.',
    sharp: 'A config file error caused the deployment failure.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },
  {
    id: 'wordy-016',
    category: 'wordy',
    weak: 'Each and every single member of the team will be required to provide and submit a detailed and comprehensive summary of their individual progress on a weekly basis.',
    sharp: 'Every team member must submit a weekly progress summary.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'wordy-017',
    category: 'wordy',
    weak: 'The new system has the ability to be able to process and handle a significantly larger number of transactions per second compared to the old one.',
    sharp: 'The new system processes more transactions per second.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Strong verb choice'],
  },
  {
    id: 'wordy-018',
    category: 'wordy',
    weak: 'I wanted to follow up and circle back on the conversation that we had previously regarding the matter of the budget that was discussed in last week\'s meeting.',
    sharp: 'Following up on the budget discussion from last week.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },

  // ============================================================
  // WEAK OPENING (18 pairs)
  // ============================================================
  {
    id: 'weak-open-001',
    category: 'weak-opening',
    weak: 'So, um, I just wanted to quickly talk about something that I noticed the other day.',
    sharp: 'I found a critical issue in our payment flow.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'weak-open-002',
    category: 'weak-opening',
    weak: 'I don\'t know if this is the right time to bring this up, but...',
    sharp: 'We need to discuss the budget shortfall.',
    principles: ['Lead with the point', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'weak-open-003',
    category: 'weak-opening',
    weak: 'Sorry to bother you, but I was wondering if I could maybe ask you something.',
    sharp: 'I have a question about the deployment schedule.',
    principles: ['Lead with the point', 'Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'weak-open-004',
    category: 'weak-opening',
    weak: 'This might be a stupid question, but does anyone know how the caching layer works?',
    sharp: 'How does the caching layer work?',
    principles: ['Lead with the point', 'Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'weak-open-005',
    category: 'weak-opening',
    weak: 'I\'m not sure if you\'ve seen this already, but there\'s something going on with the dashboard.',
    sharp: 'The dashboard is displaying stale data since yesterday.',
    principles: ['Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'weak-open-006',
    category: 'weak-opening',
    weak: 'Hey, so, I was just thinking, and this might not be relevant, but I had an idea about the onboarding flow.',
    sharp: 'I have an idea to cut onboarding time in half.',
    principles: ['Lead with the point', 'Cut hedges (I think, basically, probably)', 'Be specific, not vague'],
  },
  {
    id: 'weak-open-007',
    category: 'weak-opening',
    weak: 'I hope this email finds you well. I wanted to reach out regarding a matter that has come to my attention.',
    sharp: 'Our SSL certificate expires Friday. Here\'s the renewal plan.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'weak-open-008',
    category: 'weak-opening',
    weak: 'OK, so, like, I have a lot of thoughts about this, but first let me give some background.',
    sharp: 'We should cancel the vendor contract. Here\'s why.',
    principles: ['Lead with the point', 'Short and declarative'],
  },
  {
    id: 'weak-open-009',
    category: 'weak-opening',
    weak: 'I\'m not really sure how to say this, but I\'ve been feeling like something is off with the project.',
    sharp: 'The project is behind schedule and at risk of missing the launch date.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'weak-open-010',
    category: 'weak-opening',
    weak: 'So I\'ve been meaning to bring this up for a while now, and I finally have a chance to mention it.',
    sharp: 'Our CI pipeline takes 45 minutes. We can cut it to 15.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'weak-open-011',
    category: 'weak-opening',
    weak: 'I apologize in advance if this comes across the wrong way, but I have some feedback.',
    sharp: 'Your pull requests need more descriptive commit messages.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'weak-open-012',
    category: 'weak-opening',
    weak: 'Well, it\'s a long story, but let me try to explain what happened.',
    sharp: 'The deploy failed because we skipped staging. Here\'s what happened.',
    principles: ['Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'weak-open-013',
    category: 'weak-opening',
    weak: 'Just to preface this, I\'m not trying to point fingers or blame anyone, but...',
    sharp: 'The QA process broke down last sprint. Let\'s fix it.',
    principles: ['Lead with the point', 'Short and declarative', 'Strong verb choice'],
  },
  {
    id: 'weak-open-014',
    category: 'weak-opening',
    weak: 'This is probably obvious to everyone, but I think it bears repeating.',
    sharp: 'Never push to production on Fridays.',
    principles: ['Lead with the point', 'Short and declarative', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'weak-open-015',
    category: 'weak-opening',
    weak: 'Not to be that person, but I noticed something during the demo that I want to share with the team.',
    sharp: 'The demo exposed a data leak: user emails are visible in the API response.',
    principles: ['Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'weak-open-016',
    category: 'weak-opening',
    weak: 'Before I start, I just want to say that I really appreciate everyone taking the time to be here today.',
    sharp: 'Revenue dropped 12% last month. Here is our recovery plan.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'weak-open-017',
    category: 'weak-opening',
    weak: 'This is kind of random, but I was browsing the app last night and I noticed something weird.',
    sharp: 'The search feature returns duplicate results when filtering by date.',
    principles: ['Lead with the point', 'Be specific, not vague'],
  },
  {
    id: 'weak-open-018',
    category: 'weak-opening',
    weak: 'I know we\'re all busy and have a lot on our plates, but if I could just have a minute of your time.',
    sharp: 'I need one minute. The staging environment is down.',
    principles: ['Lead with the point', 'Short and declarative', 'Be specific, not vague'],
  },

  // ============================================================
  // ADDITIONAL MIXED PAIRS (to exceed 100 total)
  // ============================================================
  {
    id: 'hedge-021',
    category: 'hedging',
    weak: 'I think it\'s probably fair to say that most people would agree the onboarding experience isn\'t ideal.',
    sharp: 'The onboarding experience is poor.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'vague-019',
    category: 'vague',
    weak: 'The team morale is not where we want it to be.',
    sharp: 'Three engineers have asked to transfer teams this month. Morale is a problem.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'passive-019',
    category: 'passive',
    weak: 'The email was sent to the wrong distribution list and confidential information was exposed.',
    sharp: 'Someone sent the email to the wrong list and exposed confidential information.',
    principles: ['Use active voice', 'One idea per sentence'],
  },
  {
    id: 'wordy-019',
    category: 'wordy',
    weak: 'I would appreciate it if you could take a moment to review and provide your thoughts, feedback, and any suggestions you might have on the attached document at your earliest convenience.',
    sharp: 'Please review the attached document and share feedback.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'ramble-019',
    category: 'rambling',
    weak: 'I was at a conference last week and I met this guy who works at a company that does exactly what we\'re trying to build, and they told me it took them two years and a team of 20, and that got me thinking that maybe we\'re underestimating the scope of this project.',
    sharp: 'A competitor took two years and 20 engineers to build what we\'re attempting. We are underestimating the scope.',
    principles: ['Lead with the point', 'One idea per sentence', 'Short and declarative'],
  },
  {
    id: 'weak-open-019',
    category: 'weak-opening',
    weak: 'Sorry, I know you\'re really busy, and this probably isn\'t the best time, but I was hoping to chat.',
    sharp: 'Do you have five minutes? I need your input on the architecture decision.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'hedge-022',
    category: 'hedging',
    weak: 'I\'m not totally sure, but I think maybe the reason the tests are failing could potentially be related to the new dependency.',
    sharp: 'The new dependency is breaking the tests.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative', 'Lead with the point'],
  },
  {
    id: 'vague-020',
    category: 'vague',
    weak: 'We had a productive conversation with the client.',
    sharp: 'The client agreed to extend the contract for two years and increase their spend by 30%.',
    principles: ['Be specific, not vague'],
  },
  {
    id: 'passive-020',
    category: 'passive',
    weak: 'The deadline was missed and the client was not informed until the following week.',
    sharp: 'We missed the deadline and waited a week to tell the client.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'wordy-020',
    category: 'wordy',
    weak: 'It goes without saying that the security and protection of our users\' personal data and information is of the utmost and highest importance to us.',
    sharp: 'User data security is our top priority.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers'],
  },
  {
    id: 'ramble-020',
    category: 'rambling',
    weak: 'I was looking at our competitors\' websites and I noticed they all have this feature where you can export data to CSV, and I checked and we don\'t have that, and I know some customers have asked for it, so I was thinking maybe we should add it to the backlog.',
    sharp: 'Customers are requesting CSV export. Every competitor has it. We should add it to the backlog.',
    principles: ['Lead with the point', 'One idea per sentence', 'Short and declarative'],
  },
  {
    id: 'weak-open-020',
    category: 'weak-opening',
    weak: 'I\'m sure everyone here knows more about this than I do, but I wanted to share my perspective.',
    sharp: 'Here\'s what I see: we\'re solving the wrong problem.',
    principles: ['Lead with the point', 'Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'hedge-023',
    category: 'hedging',
    weak: 'Correct me if I\'m wrong, but I think we might possibly be approaching this from the wrong angle.',
    sharp: 'We\'re approaching this wrong.',
    principles: ['Cut hedges (I think, basically, probably)', 'Short and declarative'],
  },
  {
    id: 'vague-021',
    category: 'vague',
    weak: 'The release went OK but there were a few things.',
    sharp: 'The release hit three bugs: broken search, slow checkout, and a login crash on Safari.',
    principles: ['Be specific, not vague'],
  },
  {
    id: 'wordy-021',
    category: 'wordy',
    weak: 'At the end of the day, when all is said and done, I think the bottom line is that we need to focus more on the customer.',
    sharp: 'We need to focus on the customer.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Cut hedges (I think, basically, probably)'],
  },
  {
    id: 'ramble-021',
    category: 'rambling',
    weak: 'So I had this conversation with a user at the conference, and they were telling me about how they use our product, and it turns out they have this whole workaround where they export data, modify it in Excel, and re-import it, because our bulk edit feature doesn\'t support what they need.',
    sharp: 'Users are exporting data to Excel for bulk edits because our bulk edit feature is too limited. We should fix it.',
    principles: ['Lead with the point', 'One idea per sentence'],
  },
  {
    id: 'passive-021',
    category: 'passive',
    weak: 'It was brought to our attention that unauthorized access to the admin panel had been obtained.',
    sharp: 'An unauthorized user accessed the admin panel.',
    principles: ['Use active voice', 'Short and declarative', 'Lead with the point'],
  },
  {
    id: 'weak-open-021',
    category: 'weak-opening',
    weak: 'Good morning everyone, thanks for joining. Before we get started, I just want to set some context for what I\'m about to share.',
    sharp: 'We lost our biggest client yesterday. Here is the recovery plan.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'hedge-024',
    category: 'hedging',
    weak: 'I\'m no designer, but I feel like the color scheme might be somewhat difficult for some users to read.',
    sharp: 'The color scheme fails WCAG contrast requirements.',
    principles: ['Cut hedges (I think, basically, probably)', 'Be specific, not vague', 'Short and declarative'],
  },
  {
    id: 'vague-022',
    category: 'vague',
    weak: 'We should explore opportunities in the mobile space.',
    sharp: '40% of our traffic comes from mobile, but we have no mobile app. We should build one.',
    principles: ['Be specific, not vague', 'One idea per sentence'],
  },
  {
    id: 'wordy-022',
    category: 'wordy',
    weak: 'With regard to the matter of the upcoming annual company-wide retreat, I wanted to bring to your attention the fact that we will need to finalize the venue selection process.',
    sharp: 'We need to pick the retreat venue.',
    principles: ['Short and declarative', 'Remove unnecessary qualifiers', 'Lead with the point'],
  },
  {
    id: 'passive-022',
    category: 'passive',
    weak: 'Feedback was gathered from users and it was incorporated into the redesign.',
    sharp: 'We gathered user feedback and incorporated it into the redesign.',
    principles: ['Use active voice', 'Short and declarative'],
  },
  {
    id: 'ramble-022',
    category: 'rambling',
    weak: 'You know how we\'ve been talking about improving our monitoring? Well, I looked into Datadog and also checked out Grafana and New Relic, and they all have pros and cons, but I think Datadog might be the best fit because it integrates well with our stack, though it is more expensive.',
    sharp: 'I evaluated Datadog, Grafana, and New Relic. Datadog fits our stack best despite costing more. I recommend it.',
    principles: ['Lead with the point', 'One idea per sentence'],
  },
  {
    id: 'weak-open-022',
    category: 'weak-opening',
    weak: 'First of all, let me say that I have a huge amount of respect for everyone on this team and the work you do.',
    sharp: 'We shipped 40% fewer features this quarter. Let\'s diagnose why.',
    principles: ['Lead with the point', 'Be specific, not vague', 'Short and declarative'],
  },
];
