export interface SpeakAloudPrompt {
  id: string;
  type: 'defend' | 'attack' | 'explain' | 'persuade';
  topic: string;
  side: string;
  timeSeconds: number;
  modelArgument: string;
  checklist: string[];
}

export const speakAloudChecklist = [
  'Did I lead with my point?',
  'Did I avoid filler words?',
  'Did I stay under 3 main points?',
  'Did I land my ending clean?',
  'Did I pause instead of saying "um"?',
] as const;

export const speakAloudPrompts: SpeakAloudPrompt[] = [
  {
    id: 'sa-1',
    type: 'defend',
    topic: 'College is a waste of money',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "The average student graduates with $30,000 in debt for a degree that half of employers say doesn't prepare graduates for work. Meanwhile, plumbers, electricians, and coders without degrees are out-earning their peers with zero debt. College isn't education — it's credentialism. You're paying six figures for a piece of paper that Google, Apple, and IBM no longer require. The real waste isn't skipping college. It's spending four years and a mortgage-sized loan to delay adulthood.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-2',
    type: 'attack',
    topic: 'Social media is harmless',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Teen depression has doubled since 2012 — the year smartphones became ubiquitous. Instagram's own research showed it makes one in three teenage girls feel worse about their bodies. Social media isn't a tool; it's an attention casino designed by neuroscientists to be addictive. Harmless? Tobacco companies said the same thing for decades. The data is in, and it's devastating.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-3',
    type: 'defend',
    topic: 'Remote work is superior to office work',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Remote workers save 40 minutes daily on commuting — that's 160 hours a year returned to their lives. Stanford research shows a 13% productivity increase. Companies save $11,000 per remote worker annually. And employees report higher job satisfaction. The office isn't about productivity — it's about control. Managers who need to see you working are measuring presence, not output.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-4',
    type: 'attack',
    topic: 'Everyone should learn to code',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Not everyone needs to code, just like not everyone needs to be an electrician. The 'learn to code' movement is tech industry propaganda — it floods the market with junior developers, driving down wages. What people actually need is digital literacy: understanding how technology works, not writing JavaScript. Teaching everyone to code is like teaching everyone to build cars when they just need a driver's license.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-5',
    type: 'defend',
    topic: 'Cash is better than credit cards',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "When you pay with cash, you spend 12-18% less. It's called the pain of paying — handing over physical money triggers loss aversion that a card swipe doesn't. Credit card companies make their money on people who can't control spending. Cash is a budget you can see and feel. It's a system that works with human psychology instead of against it. There's a reason Dave Ramsey's first rule is to cut up the cards.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-6',
    type: 'explain',
    topic: 'Why reading books is better than consuming short-form content',
    side: 'Explain your position',
    timeSeconds: 60,
    modelArgument: "Books train sustained attention. Short-form content trains distraction. Your brain physically restructures based on how you use it — it's called neuroplasticity. Every TikTok scroll reinforces the pattern of seeking novelty over depth. Books do the opposite: they force you to sit with one idea, build on it, and think. You can't develop nuanced thinking in 60-second intervals. Depth requires duration.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-7',
    type: 'persuade',
    topic: 'Everyone should track their spending for 30 days',
    side: 'Persuade someone to do this',
    timeSeconds: 60,
    modelArgument: "Most people can't tell you within $500 what they spent last month. That's not a budgeting problem — it's an awareness problem. Track every dollar for 30 days and you'll find $200-400 in spending you didn't realize was happening. Subscriptions you forgot about, impulse purchases that felt small in the moment. You're not broke. You just can't see where the money's going. Thirty days of tracking fixes that permanently.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-8',
    type: 'defend',
    topic: 'Failure is more valuable than success',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Success teaches you nothing — it just confirms what you already believe. Failure forces recalibration. Every successful person has a list of failures that shaped them: Jobs was fired from Apple, Jordan was cut from his high school team, Rowling was rejected by 12 publishers. The lesson isn't that failure leads to success. It's that failure is the only reliable teacher. Success makes you complacent. Failure makes you sharp.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-9',
    type: 'attack',
    topic: 'Hustle culture is the path to success',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Hustle culture confuses movement with progress. Working 80 hours a week doesn't make you productive — it makes you exhausted. Burnout isn't a badge of honor; it's a failure of strategy. The most successful people don't out-work everyone — they out-think everyone. Warren Buffett reads six hours a day. Bill Gates takes two-week think weeks. Hustle culture is what happens when people mistake busyness for effectiveness.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-10',
    type: 'defend',
    topic: 'Physical books are better than e-readers',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Studies show better retention with physical books — the spatial memory of where something appeared on a page aids recall. Physical books have no notifications, no battery, no screen fatigue. They're a technology that's been perfected over centuries. E-readers are just screens, and we already spend 11 hours a day on screens. A physical book is one of the last spaces where your attention isn't being sold to advertisers.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-11',
    type: 'persuade',
    topic: 'You should wake up before 6 AM',
    side: 'Persuade someone',
    timeSeconds: 60,
    modelArgument: "The hour before the world wakes up is the only hour that's truly yours. No emails, no messages, no demands. That's when you invest in yourself — exercise, reading, thinking. Every CEO, athlete, and high performer talks about their morning routine for a reason. It's not about sleeping less. It's about starting your day on offense instead of defense. You either run the morning, or the morning runs you.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-12',
    type: 'attack',
    topic: 'Grades accurately measure intelligence',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Grades measure compliance, not intelligence. They measure who can memorize information for a test and regurgitate it on schedule. Einstein failed entrance exams. Edison was called 'addled' by teachers. Grades reward a specific type of learner in a specific type of system. The students with the best grades often become employees of the students who dropped out. That tells you everything about what grades actually measure.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-13',
    type: 'defend',
    topic: 'Cooking at home is a necessary life skill',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "If you can't feed yourself, you're dependent. Not just financially — a restaurant meal costs 3-5x a home-cooked one — but psychologically. Cooking is the most fundamental act of self-sufficiency. It connects you to what you put in your body, saves you thousands annually, and is the single best way to eat healthier. An adult who can't cook a basic meal has outsourced one of the most basic functions of being alive.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-14',
    type: 'explain',
    topic: 'Why you should learn to say no',
    side: 'Explain your position',
    timeSeconds: 60,
    modelArgument: "Every yes is a no to something else. When you say yes to a meeting you don't need, you're saying no to deep work. When you say yes to a social obligation you dread, you're saying no to rest. The most productive people in the world are ruthless with their no. It's not selfish — it's strategic. Your time is finite. Protecting it isn't rude. It's responsible.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-15',
    type: 'defend',
    topic: 'Journaling changes your life',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Your brain is a terrible storage device but an incredible processor. Journaling gets thoughts out of the loop and onto paper where you can actually examine them. Studies show journaling reduces anxiety, improves immune function, and increases emotional processing speed. It's not about writing well. It's about thinking clearly. Ten minutes of journaling does what an hour of ruminating can't.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-16',
    type: 'attack',
    topic: 'Following your passion is good career advice',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Passion doesn't pay bills — skills do. 'Follow your passion' is survivorship bias disguised as advice. For every musician who made it, there are ten thousand who didn't. Cal Newport's research shows passion follows mastery, not the other way around. Get good at something valuable, and passion follows. Start with passion alone, and you get a hobby that doesn't pay rent.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-17',
    type: 'persuade',
    topic: 'Delete social media for 30 days',
    side: 'Persuade someone',
    timeSeconds: 60,
    modelArgument: "You spend an average of 2.5 hours a day on social media. That's 38 full days a year. Delete the apps for 30 days and watch what happens: you'll read more, sleep better, compare yourself less, and reclaim an hour of mental clarity every morning. If it's truly valuable, you can always re-download it. But most people who try this don't go back. They realize the thing they thought they needed was actually the thing draining them.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-18',
    type: 'defend',
    topic: 'Cold showers have real benefits',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Cold exposure increases norepinephrine by 200-300%, boosting alertness and mood for hours. It activates brown fat, which burns calories. It reduces inflammation. But the real benefit isn't physical — it's psychological. Every cold shower is a micro-decision to choose discomfort. You start your day by doing something hard. That sets a tone. People who can't tolerate two minutes of cold water will struggle with much bigger discomforts.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-19',
    type: 'explain',
    topic: 'Why you should travel solo at least once',
    side: 'Explain your position',
    timeSeconds: 60,
    modelArgument: "Solo travel strips away every social crutch. There's no friend to decide for you, no partner to navigate for you. Every conversation, every decision, every problem is yours alone. That's not lonely — it's liberating. You discover what you actually enjoy versus what you go along with. You learn to be comfortable with yourself. And you come back with a confidence that group travel never builds.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-20',
    type: 'attack',
    topic: 'Money can\'t buy happiness',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Money absolutely buys happiness — up to about $75,000, it's a near-linear relationship. Poverty is miserable. Financial stress destroys marriages, health, and mental well-being. What money can't buy is fulfillment beyond a certain point. But conflating those two things is dangerous because it lets wealthy people moralize about poverty. Tell a single mom working three jobs that money can't buy happiness. It can buy childcare, healthcare, and peace of mind.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-21',
    type: 'defend',
    topic: 'Everyone should lift weights',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "After age 30, you lose 3-8% of muscle mass per decade. By 70, weak people can't get off the toilet without help. Resistance training reverses this. It's the single best predictor of quality of life in old age. It builds bone density, prevents falls, improves metabolic health, and reduces depression. Cardio keeps your heart going. Weights keep you independent. It's not about looking good — it's about being functional at 80.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-22',
    type: 'persuade',
    topic: 'Read one book a month',
    side: 'Persuade someone',
    timeSeconds: 60,
    modelArgument: "One book a month is 12 books a year. In five years, that's 60 books — more than most people read in a lifetime. That's 60 people's life work distilled into a few hundred pages each. The compounding effect is staggering. Every book changes how you see one thing, and over time, you see everything differently. Twenty minutes a day. That's all it takes. You have the time — you're just giving it to your phone.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-23',
    type: 'attack',
    topic: 'Work-life balance is achievable for everyone',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Work-life balance is a myth sold by lifestyle brands to people who feel guilty about working. The reality? Building anything meaningful requires seasons of imbalance. Every founder, artist, and athlete went through years where work consumed everything. Balance isn't the goal — intentionality is. Know when to push and when to rest. But pretending you can give everything equal attention all the time is a recipe for mediocrity in every area.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-24',
    type: 'defend',
    topic: 'Boredom is good for you',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "We've eliminated boredom with smartphones and we've eliminated creativity along with it. Boredom is the brain's incubation state — it's when your mind makes unexpected connections. Newton discovered gravity during idle time. Archimedes had his eureka moment in a bath. Every time you fill a quiet moment with your phone, you're interrupting your brain's most creative mode. Boredom isn't a problem to solve. It's a resource to protect.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-25',
    type: 'explain',
    topic: 'Why small talk matters more than you think',
    side: 'Explain your position',
    timeSeconds: 60,
    modelArgument: "Small talk isn't meaningless — it's the gateway protocol of human connection. Before anyone trusts you with big talk, they need to know you can handle small talk. It's a social handshake. People who dismiss it as shallow are usually people who struggle with it. The best conversationalists, negotiators, and leaders are all excellent at small talk. It's not about the weather. It's about showing you can connect on any level.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-26',
    type: 'defend',
    topic: 'Discomfort is the price of growth',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Your comfort zone is a prison that feels like home. Every skill you're proud of was once something you were terrible at. Every strong relationship survived uncomfortable conversations. Every career leap required the terror of leaving something safe. Growth doesn't happen in comfort — it happens at the edge of it. The question isn't whether growth is uncomfortable. It's whether you're willing to be uncomfortable on purpose.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-27',
    type: 'attack',
    topic: 'AI will solve all our problems',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Technology doesn't solve problems — it transforms them. Social media was supposed to connect us; it isolated us. The internet was supposed to make us informed; it made us polarized. AI will follow the same pattern. It'll solve certain problems brilliantly while creating new ones we haven't imagined. Every tool amplifies the user. Give powerful AI to a flawed society, and you get amplified flaws at scale. The bottleneck was never intelligence. It was wisdom.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-28',
    type: 'persuade',
    topic: 'Start a side project this week',
    side: 'Persuade someone',
    timeSeconds: 60,
    modelArgument: "Your job builds someone else's dream. A side project builds yours. It doesn't need to make money — it needs to make you think differently. The skills you develop, the problems you solve, the identity you build — that's yours forever. Most people's biggest regret isn't failure. It's never starting. You have evenings and weekends. You have skills. The only thing you're missing is the decision to begin.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-29',
    type: 'defend',
    topic: 'Handwriting is still important in the digital age',
    side: 'Defend this position',
    timeSeconds: 60,
    modelArgument: "Studies consistently show handwriting improves retention and comprehension over typing. When you type, you transcribe. When you write by hand, you synthesize — your brain has to process and compress because your hand can't keep up. That compression is learning. Princeton researchers found that laptop note-takers performed worse on conceptual questions despite taking more notes. More isn't better. Processing is better. And handwriting forces processing.",
    checklist: [...speakAloudChecklist],
  },
  {
    id: 'sa-30',
    type: 'attack',
    topic: 'Multitasking makes you more productive',
    side: 'Attack this position',
    timeSeconds: 60,
    modelArgument: "Multitasking doesn't exist. What you're actually doing is task-switching, and every switch costs you 23 minutes of refocused attention. That's not productive — it's destructive. Gloria Mark's research shows the average worker switches tasks every three minutes. People who think they're multitasking are actually doing multiple things poorly while feeling productive. Single-tasking is slower in theory and dramatically faster in practice.",
    checklist: [...speakAloudChecklist],
  },
];
